### ISSUE TITLE
How to use nested map?

### ISSUE THREAD

**Issue by timlincool** [OpenHFT/Chronicle-Map#100]
How to use nested map?

for example

I try these, but don't work.

```

		 ChronicleMap<String, String> map = ChronicleMap.of(String.class, String.class).entries(10).averageKeySize(1).averageValueSize(1).create();
		 map.put("test", "test");
		 ChronicleMap<String, ChronicleMap > nestedMap = ChronicleMap.of(String.class, ChronicleMap.class).entries(100).averageKeySize(1).averageValueSize(1).actualSegments(3).create();			
		 nestedMap.put("test", map);
		 System.out.println(nestedMap);
```

got exception 

```
Exception in thread "main" java.lang.ClassCastException: net.openhft.chronicle.map.VanillaChronicleMap cannot be cast to java.io.Serializable
	at net.openhft.chronicle.hash.serialization.impl.SerializableDataAccess.getData(SerializableDataAccess.java:32)
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:564)
```

**Comment by peter-lawrey** [comment]
Hello,

You can't put a ChronicleMap inside another ChronicleMap.

You can value a Map as a value, however you would need to put it again
after getting.

Peter.

**Comment by leventov** [comment]
@timlincool you can also find this discussion useful: http://stackoverflow.com/questions/36483569/multimaps-in-chroniclemap
