### ISSUE TITLE
Windows 7 can't create map to file

### ISSUE THREAD

**Issue by colomb001** [OpenHFT/Chronicle-Map#113]
When running the following code under windows 7 x64
```
ChronicleMapBuilder<String, String> builder = ChronicleMapBuilder.of( String.class, String.class )
    .name( "test-map" )
    .averageKeySize( 50 )
    .averageValueSize( 30_000 )
    .entries( 2602 );

ChronicleMap<String, String> testMap = builder.createPersistedTo( new File( "C:/temp/test-map.dat" ) );
System.out.println( testMap.size() );
```

this exception is thrown:
```
Exception in thread "main" java.io.IOException: The process cannot access the file because another process has locked a portion of the file.
	at net.openhft.chronicle.hash.impl.util.jna.WindowsMsync.msync(WindowsMsync.java:53)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:858)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:846)
	at net.openhft.chronicle.map.ChronicleMapBuilder.commitChronicleMapReady(ChronicleMapBuilder.java:404)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1675)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1537)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1472)
	at scratch.main(scratch.java:20)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```
Change the number of entries to 2601, and the code executes as expected. It appears that chronicle can't create a map to file when the resulting file on disk is around 128MB under windows 7. I thought this might be related to issue #8, but a different exception was being thrown for that issue. This works under windows 10. I'm using Java 8u111 and Chronicle Map 3.12.0.

Of note, the file still gets created on disk even when the exception is thrown. Make sure to delete it when rerunning the code snippet.

**Comment by leventov** [comment]
I'm not an Windows expert nor have a Windows 7 machine for testing. From your issue description (ok if file < 128 mb, ok on Windows 10) seems that that "another process" which locked a portion of a file is some Windows system process. I don't know what kind of process it could be. You should probably consult with professional Windows administrators or experts on specialized forums.

Probably you could resolve this issue by adding another condition here: https://github.com/OpenHFT/Chronicle-Map/blob/master/src/main/java/net/openhft/chronicle/hash/impl/util/jna/WindowsMsync.java#L44 and adding some wait between retries. Build Chronicle Map from source (`mvn clean install`) and experiment.

If you succeed I will be happy to accept a patch.

**Comment by leventov** [comment]
Or maybe increase number of retires from 3 to, say, 10, and add a 10 milliseconds timeout between retries. Maybe it would help.

**Comment by colomb001** [comment]
I'll give that a shot and report back.

**Comment by minborg** [comment]
I am closing this @colomb001 . Please reopen if still relevant and report back.

**Comment by colomb001** [comment]
I'm sorry. We no longer had any Windows 7 machines in the office to test.
Thank you for closing.

Alex
