### ISSUE TITLE
getUsing + indexed fields do not work

### ISSUE THREAD

**Issue by deridex** [OpenHFT/Chronicle-Map#117]
I'm experiencing some unexpected behavior when trying to combine `getUsing` with an indexed field.

The following type works as the value in a chronicle map:

```java
public interface Value {
    int getX();

    void setX(int i);

    @Array(length = 8)
    LongValue getIdAt(int index);

    void setIdAt(int index, LongValue id);
}
```

Rather than create a new `LongValue` on every get, I'd like to use an existing instance. chronicle-values documentation includes:

`getUsing<FieldName>[At]([int index, ]Type using)`

So, I should be able to use the following as the chronicle-map value type:

```java
public interface Value {
    int getX();

    void setX(int i);

    @Array(length = 8)
    LongValue getUsingIdAt(int index, LongValue using);

    void setIdAt(int index, LongValue id);
}
```

But then map construction fails with:

```
Exception in thread "main" java.lang.IllegalStateException: Value size in serialized form must be configured in ChronicleMap, at least approximately.
Use builder.averageValue()/.constantValueSizeBySample()/.averageValueSize() methods to configure the size
	at net.openhft.chronicle.map.ChronicleMapBuilder.preMapConstruction(ChronicleMapBuilder.java:1838)
	at net.openhft.chronicle.map.ChronicleMapBuilder.preMapConstruction(ChronicleMapBuilder.java:1823)
	at net.openhft.chronicle.map.ChronicleMapBuilder.newMap(ChronicleMapBuilder.java:1812)
	at net.openhft.chronicle.map.ChronicleMapBuilder.lambda$createWithFile$99(ChronicleMapBuilder.java:1568)
	at net.openhft.chronicle.map.ChronicleMapBuilder.lambda$fileLockedIO$98(ChronicleMapBuilder.java:260)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at net.openhft.chronicle.map.ChronicleMapBuilder.fileLockedIO(ChronicleMapBuilder.java:257)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1566)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1484)
```

Using `void` as the return type for the indexed getter doesn't help.

Do indexed fields support `getUsing`?

**Comment by leventov** [comment]
This is a bug in Chronicle Values, such interface should be supported. To test it more explicitly and see the problem, call `Values.heapClassFor(Value.class);` and `Values.nativeClassFor(Value.class);`.

While this bug is not fixed yet, you can use primitive long:
```java
public interface Value {
  int getX();

  void setX(int i);

  @Array(length = 8)
  long getIdAt(int index);

  void setIdAt(int index, long id);
}
```

**Comment by deridex** [comment]
> While this bug is not fixed yet, you can use primitive long:

I used the longs to demonstrate the problem. I was actually hoping to use a more complex object as the indexed type. I'll find a way to work around it, in the meantime.

Thanks for the response!

**Comment by minborg** [comment]
I am closing this issue as there seems to be another way of doing it as indicated by @deridex . Please reopen if not.
