### ISSUE TITLE
net.openhft.chronicle.bytes.UTFDataFormatRuntimeException: malformed input around byte

### ISSUE THREAD

**Issue by EboYu** [OpenHFT/Chronicle-Map#120]
Hi all,
 I use the ```CharSequenceArrayBytesMarshaller``` in the README, but I got the below error when I try to get data in the Chronicle Map. The version of Chronicle-Map that I used is ```3.13.0```. 
Is there something wrong with the ```CharSequenceArrayBytesMarshaller```? or Any solution for this error?
```
net.openhft.chronicle.bytes.UTFDataFormatRuntimeException: malformed input around byte 6 was 103
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf82(BytesInternal.java:457)
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8_SB1(BytesInternal.java:383)
	at net.openhft.chronicle.bytes.BytesInternal.parseUtf8(BytesInternal.java:123)
	at net.openhft.chronicle.bytes.StreamingDataInput.readUtf8(StreamingDataInput.java:184)
	at rule.CharSequenceArrayBytesMarshaller.read(CharSequenceArrayBytesMarshaller.java:60)
	at rule.CharSequenceArrayBytesMarshaller.read(CharSequenceArrayBytesMarshaller.java:27)
```
```
try (ChronicleMap<String, CharSequence[]> map = ChronicleMap
                .of(String.class, CharSequence[].class)
                .averageKey("fruits")
                .valueMarshaller(CharSequenceArrayBytesMarshaller.INSTANCE)
                .averageValue(new CharSequence[]{"banana", "pineapple"})
                .entries(2)
                .create()) {
            map.put("fruits", new CharSequence[]{"banana", "pineapple"});
            map.put("vegetables", new CharSequence[] {"carrot", "potato"});
            map.get("fruits");
            map.get("vegetables");
        }
```
```
public final class CharSequenceArrayBytesMarshaller
        implements BytesWriter<CharSequence[]>, BytesReader<CharSequence[]>,
        ReadResolvable<CharSequenceArrayBytesMarshaller> {

    static final CharSequenceArrayBytesMarshaller INSTANCE = new CharSequenceArrayBytesMarshaller();

    private CharSequenceArrayBytesMarshaller() {}

    @Override
    public void write(Bytes out, @NotNull CharSequence[] toWrite) {
        out.writeInt(toWrite.length);
        for (CharSequence cs : toWrite) {
            // Assume elements non-null for simplicity
            Objects.requireNonNull(cs);
            out.writeUtf8(cs);
        }
    }

    @NotNull
    @Override
    public CharSequence[] read(Bytes in, @Nullable CharSequence[] using) {
        int len = in.readInt();
        if (using == null)
            using = new CharSequence[len];
        if (using.length != len)
            using = Arrays.copyOf(using, len);
        for (int i = 0; i < len; i++) {
            CharSequence cs = using[i];
            if (cs instanceof StringBuilder) {
                in.readUtf8((StringBuilder) cs);
            } else {
                StringBuilder sb = new StringBuilder(0);
                in.readUtf8(sb);
                using[i] = sb;
            }
        }
        return using;
    }

    @Override
    public void writeMarshallable(@NotNull WireOut wireOut) {
        // no fields to write
    }

    @Override
    public void readMarshallable(@NotNull WireIn wireIn) {
        // no fields to read
    }

    @Override
    public CharSequenceArrayBytesMarshaller readResolve() {
        return INSTANCE;
    }
}
```

**Comment by leventov** [comment]
I cannot reproduce this issue, the following test passes on my dev machine: https://gist.github.com/leventov/de09631cc7f16a7357d5eb942217c88d which OS do you use?

**Comment by minborg** [comment]
This appears to be fixed. Please reopen if not.
