### ISSUE TITLE
Storing byte[] keys/values results in Exception

### ISSUE THREAD

**Issue by mstrap** [OpenHFT/Chronicle-Map#125]
Storing byte[] keys/values does not work. Following code snippet

```		
final File cacheRoot = new File("d:/temp/chronicle3");
ChronicleMapBuilder<byte[], byte[]> shaToNodeBuilder =
		ChronicleMapBuilder.of(byte[].class, byte[].class)
				.name("bytes-to-bytes")
				.entries(1000000).
				averageKeySize(20).
				averageValueSize(30);

ChronicleMap<byte[], byte[]> shaToNode =
		shaToNodeBuilder.createPersistedTo(cacheRoot);

shaToNode.put("1".getBytes(), "2".getBytes());

shaToNodeBuilder.createPersistedTo(cacheRoot);
```

results in:

```
Exception in thread "main" java.lang.IllegalStateException: Expected a } was ],
  keySizeMarshaller: !net.openhft.chronicle.hash.serialization.impl.StopBitSizeMarshaller {
  },
  keyReader: !net.openhft.chronicle.hash.serialization.impl.ByteArraySizedReader {
  },
  keyDataAccess: !net.openhft.chronicle.hash.serialization.impl.ByteArrayDataAccess {
  },
  checksumEntries: true,
  actualSegments: 256,
  hashSplitting: !net.openhft.chronicle.hash.impl.HashSplitting$ForPowerOf2Segments {
    bits: 8
  },
  chunkSize: 8,
  maxChunksPerEntry: 32886,
  actualChunksPerSegmentTier: 32886,
  segmentHeaderSize: 64,
  tierHashLookupValueBits: 16,
  tierHashLookupKeyBits: 16,
  tierHashLookupSlotSize: 4,
  tierHashLookupCapacity: 8192,
  maxEntriesPerHashLookup: 6553,
  tierHashLookupInnerSize: 32768,
  tierHashLookupOuterSize: 32768,
  tierFreeListInnerSize: 4112,
  tierFreeListOuterSize: 4160,
  tierEntrySpaceInnerSize: 263088,
  tierEntrySpaceInnerOffset: 0,
  tierEntrySpaceOuterSize: 263104,
  tierSize: 300096,
  maxExtraTiers: 256,
  tierBulkSizeInBytes: 9603072,
  tierBulkInnerOffsetToTiers: 0,
  tiersInBulk: 32,
  log2TiersInBulk: 5,
  valueClass: !type byte[],
  valueSizeMarshaller: !net.openhft.chronicle.hash.serialization.impl.StopBitSizeMarshaller {
  },
  valueReader: !net.openhft.chronicle.hash.serialization.impl.ByteArraySizedReader {
  },
  valueDataAccess: !net.openhft.chronicle.hash.serialization.impl.ByteArrayDataAccess {
  },
  constantlySizedEntry: false,
  alignment: 1,
  worstAlignment: 0
}

	at net.openhft.chronicle.wire.TextWire$TextValueIn.consumeAny(TextWire.java:2167)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.readLengthMarshallable(TextWire.java:2138)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.marshallable(TextWire.java:2710)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:517)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.objectWithInferredType0(TextWire.java:2996)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.objectWithInferredType(TextWire.java:2969)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.typedMarshallable(TextWire.java:2783)
	at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1756)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1555)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1484)
	at com.syntevo.git.core.node.ChronicleMapTest2.main(ChronicleMapTest2.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

Tested with:

chronicle-algorithms-1.1.8.jar
chronicle-bytes-1.8.2.jar
chronicle-core-1.8.0.jar
chronicle-map-3.13.0.jar
chronicle-threads-1.7.7.jar
chronicle-values-1.5.5.jar
chronicle-wire-1.8.4.jar
javapoet-1.5.1.jar

**Comment by leventov** [comment]
This happens because of incompatibility between Chronicle Map 3.13.0 and Chronicle Wire 1.8.4. Chronicle Map 3.13.0 is officially compatible with Wire 1.7.30. This incompatibility is going to be patched in the next released version of Chronicle Map.

**Comment by peter-lawrey** [comment]
You could try wire 1.8.4 as it fixes a few bugs.

**Comment by mstrap** [comment]
@peter-lawrey, I was using Wire 1.8.4 initially (because I was collecting information on dependencies from https://mvnrepository.com/artifact/net.openhft/chronicle-map/3.13.0 which doesn't list restrictions for the other Chronicle JARs). But as @leventov has pointed out, Wire 1.8.4 seems to have caused my issues. Either way, I've got it working now. Thanks!
