### ISSUE TITLE
NullPointerException when I run my application in a plugin environment

### ISSUE THREAD

**Issue by subodh-shrivastava** [OpenHFT/Chronicle-Map#132]
Same application works fine out of plugin environment.
Exception in thread "Thread-5" java.lang.NullPointerException
        at net.openhft.chronicle.values.ValueModel.createClass(ValueModel.java:341)
        at net.openhft.chronicle.values.ValueModel.createNativeClass(ValueModel.java:323)
        at net.openhft.chronicle.values.ValueModel.nativeClass(ValueModel.java:299)
        at net.openhft.chronicle.values.Values.nativeClassFor(Values.java:83)
        at net.openhft.chronicle.values.Values.newNativeReference(Values.java:51)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createGlobalMutableState(VanillaChronicleHash.java:340)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.initOwnTransients(VanillaChronicleHash.java:389)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.initTransients(VanillaChronicleHash.java:385)
        at net.openhft.chronicle.map.VanillaChronicleMap.initTransients(VanillaChronicleMap.java:163)
        at net.openhft.chronicle.map.VanillaChronicleMap.<init>(VanillaChronicleMap.java:116)
        at net.openhft.chronicle.map.ChronicleMapBuilder.newMap(ChronicleMapBuilder.java:1816)
        at net.openhft.chronicle.map.ChronicleMapBuilder.lambda$createWithFile$99(ChronicleMapBuilder.java:1568)
        at net.openhft.chronicle.map.ChronicleMapBuilder.lambda$fileLockedIO$98(ChronicleMapBuilder.java:260)
        at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
        at net.openhft.chronicle.map.ChronicleMapBuilder.fileLockedIO(ChronicleMapBuilder.java:257)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1566)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1484)

**Comment by RobAustin** [comment]
can you retest with the last version and let us know if it still fails.

**Comment by minborg** [comment]
I am closing this issue now @subodh-shrivastava . Please provide a test that reproduces the problem if you want to reopen the issue. Thank you.
