### ISSUE TITLE
Runtime compatibility with Java 9

### ISSUE THREAD

**Issue by mstrap** [OpenHFT/Chronicle-Map#134]
Chronicle-Map is currently not working with upcoming JRE 9. So far, I've identified following problems (tested with 9+179):

- `ByteBufferDataAccess`  is using `sun.nio.ch.DirectBuffer` which won't be accessible anymore. As `MappedByteBuffer` is the only `ByteBuffer` which is a `DirectBuffer`, this should be easy to resolve by changing `getData` to:

```
public Data<ByteBuffer> getData(@NotNull ByteBuffer instance) {
    bb = instance;
    if (instance instanceof MappedByteBuffer) {
        nativeBytesStore.init(instance, false);
        bytesStore = nativeBytesStore;
    } else {
        heapBytesStore.init(instance);
        bytesStore = heapBytesStore;
    }
    return this;
}
```

- `VanillaChronicleHash`  is using `sun.misc.Cleaner` which won't be available anymore.

**Comment by TerryW9** [comment]
Hi mstrap,

Thank you for reporting this to us.

Best Regards,
Terry

**Comment by mstrap** [comment]
I hope to have addressed both issues in my master https://github.com/mstrap/Chronicle-Map/commits/master, however when accessing an persisted map with JRE 9, I get:

`java.lang.ClassCastException: [B cannot be cast to [C
	at net.openhft.chronicle.core.util.StringUtils.extractChars(StringUtils.java:125)
	at net.openhft.chronicle.core.util.StringUtils.isEqual(StringUtils.java:100)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.consumeValue(TextWire.java:2306)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.consumeAny(TextWire.java:2286)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.consumeAny(TextWire.java:2294)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.consumeAny(TextWire.java:2233)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.readLengthMarshallable(TextWire.java:2218)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.marshallable(TextWire.java:2820)
	at net.openhft.chronicle.wire.Wires.objectMap(Wires.java:421)
	at net.openhft.chronicle.wire.Wires.object0(Wires.java:468)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:561)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.objectWithInferredType0(TextWire.java:3106)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.objectWithInferredType(TextWire.java:3079)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.typedMarshallable(TextWire.java:2893)
	at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1767)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1566)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1495)
`

Using JRE 8 on the same persisted map works fine.

Any ideas what the problem might be?

**Comment by epickrram** [comment]
Compact Strings are a new feature in JDK9, this change means that the data underlying a String object is now of type byte[] rather than char[] as it was previous to JDK9.
We are working through the Chronicle libraries making sure that they are compatible with new Java9 features. The next release of Chronicle-Core should address the issue above, as the work progresses, we will update the dependency in Chronicle-Map so that the code will run on a version 9 JDK.

**Comment by MartyIX** [comment]
@mstrap The issue may no longer exist as some changes were made in Chronicle-Core to support JDK 9.

**Comment by mstrap** [comment]
Indeed, after updating to commit 7cbc967284503648087715349ef3a4f668d1d4c4 and applying my patch bc452079c5443204b1540dc48fcafe12b4f48c64, I can successfully read/write existing and create new persistent maps. Thanks for this!

Please note that for my (updated) patch I have simply removes the `Cleaner` field, because the plain existence of the field causes following Exception:

```
java.lang.NoClassDefFoundError
	at java.base/java.lang.Class.getDeclaredFields0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredFields(Unknown Source)
	at java.base/java.lang.Class.getDeclaredFields(Unknown Source)
	at net.openhft.chronicle.wire.WireMarshaller.getAllField(WireMarshaller.java:106)
	at net.openhft.chronicle.wire.WireMarshaller.getAllField(WireMarshaller.java:105)
	at net.openhft.chronicle.wire.WireMarshaller.of(WireMarshaller.java:66)
	at net.openhft.chronicle.wire.WireMarshaller.lambda$static$0(WireMarshaller.java:45)
	at net.openhft.chronicle.core.ClassLocal.computeValue(ClassLocal.java:49)
	at java.base/java.lang.ClassValue.getFromHashMap(Unknown Source)
	at java.base/java.lang.ClassValue.getFromBackup(Unknown Source)
	at java.base/java.lang.ClassValue.get(Unknown Source)
	at net.openhft.chronicle.wire.TextWire$TextValueOut.marshallable(TextWire.java:1691)
	at net.openhft.chronicle.wire.ValueOut.typedMarshallable(ValueOut.java:411)
	at net.openhft.chronicle.map.ChronicleMapBuilder.writeHeader(ChronicleMapBuilder.java:388)
	at net.openhft.chronicle.map.ChronicleMapBuilder.lambda$createWithFile$2(ChronicleMapBuilder.java:1580)
	at net.openhft.chronicle.map.ChronicleMapBuilder.lambda$fileLockedIO$1(ChronicleMapBuilder.java:261)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(Unknown Source)
	at net.openhft.chronicle.map.ChronicleMapBuilder.fileLockedIO(ChronicleMapBuilder.java:258)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1577)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1495)
```

**Comment by MartyIX** [comment]
@mstrap Cleaner was actually wrapped in a class as far as I understand. Please see:

https://github.com/OpenHFT/Chronicle-Core/commit/5562487824052ab021409e52b4ade3bd7802d030#diff-a5ac9316046f3d0adf9d4bde88ceb9e9R15

**Comment by epickrram** [comment]
Hello,
thanks for persevering with this work. Java9 support is scheduled to be started in earnest soon. There are currently other priorities that we need to address first.

The Cleaner issue has indeed be resolved, but support for this has not yet filtered down to the various sub-projects.

**Comment by mstrap** [comment]
Thanks, @MartyIX and @epickrram, I'll wait for the chronicle-core update in this project.

**Comment by tkowalcz** [comment]
Hello, what are the plans for Java 9 support? 

I upgraded `chronicle-map` to newest version `3.14.3` which uses  `chronicle-values:1.5.5` that depends on tools.jar which is no longer available in Java9.

**Comment by peter-lawrey** [comment]
In the short term, you can pregenerate the classes needed so tools.jar
isn't needed at runtime.
Afaik the Compiler API hasn't been removed so this us most likely a
comparability problem.
Regards Peter

**Comment by dpisklov** [comment]
Core and Wire are now working with Java 11, so as Map.

**Comment by kskalski** [comment]
Does that apply to chronicle-map : 3.15.1? I do get errors about tools.jar when compiling with openjdk-11:
Could not find artifact com.sun.java:tools:jar:10.0.1 at specified path /usr/lib/jvm/java-11-openjdk-amd64/../lib/tools.jar

**Comment by dpisklov** [comment]
@kskalski no it only applies to 3.16.0-SNAPSHOT at the moment, the version with Java 11 support hasn't been released yet.

**Comment by kskalski** [comment]
Hm, I tried the snapshot 
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>testgroup</groupId>
    <artifactId>test</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>
    <name>test</name>
    <description>test</description>

    <properties>
        <java.version>10</java.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-map</artifactId>
            <version>3.16.0-SNAPSHOT</version>
        </dependency>
    </dependencies>

    <repositories>
        <repository>
            <id>Snapshot Repository</id>
            <name>Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
</project>
```
and still getting error

```
[ERROR] Failed to execute goal on project test: Could not resolve dependencies for project testgroup:test:jar:0.0.1-SNAPSHOT: Could not find artifact com.sun.java:tools:jar:10.0.1 at specified path /usr/lib/jvm/java-11-openjdk-amd64/../lib/tools.jar -> [Help 1]
```

**Comment by dpisklov** [comment]
@kskalski 
Please use exclusion for it for now until we find a better way of dealing with it:
```
<dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-map</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.java</groupId>
                    <artifactId>tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
I also fixed one more little glitch just now so with latest snapshot you should be all good

**Comment by kskalski** [comment]
Thanks, it works for me with:
```
        <dependency>
            <groupId>net.openhft</groupId>
            <artifactId>chronicle-map</artifactId>
            <version>3.16.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.sun.java</groupId>
                    <artifactId>tools</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```
