### ISSUE TITLE
Tests broken due java.lang.NoClassDefFoundError: net/openhft/chronicle/bytes/BytesComment

### ISSUE THREAD

**Issue by mstrap** [OpenHFT/Chronicle-Map#139]
I've just pulled commit 93a642054e90c0ab0145ecadb9064fafa011fced, but I see a couple tests failing. The first one is:

`Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.062 sec <<< FAILURE! - in net.openhft.chronicle.map.ChronicleMap3_12IntegerKeyCompatibilityTest
testWithChecksums(net.openhft.chronicle.map.ChronicleMap3_12IntegerKeyCompatibilityTest)  Time elapsed: 0.062 sec  <<< ERROR!
net.openhft.chronicle.hash.ChronicleHashRecoveryFailedException: java.lang.NoClassDefFoundError: net/openhft/chronicle/bytes/BytesComment
        at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1788)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1566)
        at net.openhft.chronicle.map.ChronicleMapBuilder.recoverPersistedTo(ChronicleMapBuilder.java:1532)
        at net.openhft.chronicle.map.ChronicleMapBuilder.recoverPersistedTo(ChronicleMapBuilder.java:1524)
        at net.openhft.chronicle.map.ChronicleMap3_12IntegerKeyCompatibilityTest.testWithChecksums(ChronicleMap3_12IntegerKeyCompatibilityTest.java:40)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
Caused by: java.lang.NoClassDefFoundError: net/openhft/chronicle/bytes/BytesComment
        at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1766)
        ... 28 more
Caused by: java.lang.ClassNotFoundException: net.openhft.chronicle.bytes.BytesComment
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 29 more
`

**Comment by RobAustin** [comment]
Could you retest using the latest snapshot.

**Comment by mstrap** [comment]
How would I do that? I've checked out 93a6420, invoked `mvn clean`, then `mvn deploy` and after a while will see the crash.

**Comment by dpisklov** [comment]
That is indeed latest, it seems.

**Comment by mstrap** [comment]
With 398515ca077476a5f2b710e6c9f8bb8c1522631b everything is fine again. Thanks!
