### ISSUE TITLE
invalid stream header exception at get operation from map

### ISSUE THREAD

**Issue by ergineroglu** [OpenHFT/Chronicle-Map#14]
during get operation sometimes we got IllegalStateException. 
Stack trace is below:
```
INFO   | jvm 1    | 2015/01/07 10:16:09 | java.lang.IllegalStateException: java.io.StreamCorruptedException: invalid stream header: 00000000
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.lang.io.AbstractBytes.readInstance(AbstractBytes.java:1978)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.lang.io.AbstractBytes.readEnum(AbstractBytes.java:1833)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.lang.io.AbstractBytes.readMap(AbstractBytes.java:1878)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.infoowl.inforules.model.StateRecord.readMarshallable(StateRecord.java:109)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.lang.io.serialization.impl.BytesMarshallableMarshaller.read(BytesMarshallableMarshaller.java:65)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.lang.io.serialization.impl.BytesMarshallableMarshaller.read(BytesMarshallableMarshaller.java:31)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.chronicle.hash.serialization.internal.BytesReaders$SimpleBytesReader.read(BytesReaders.java:60)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.chronicle.map.VanillaChronicleMap$Segment.readValue(VanillaChronicleMap.java:1082)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.chronicle.map.VanillaChronicleMap$Segment.readValue(VanillaChronicleMap.java:1076)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.chronicle.map.VanillaChronicleMap$Segment.onKeyPresentOnAcquire(VanillaChronicleMap.java:911)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.chronicle.map.VanillaChronicleMap$Segment.acquireWithoutLock(VanillaChronicleMap.java:869)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.chronicle.map.VanillaChronicleMap.lookupUsing(VanillaChronicleMap.java:419)
INFO   | jvm 1    | 2015/01/07 10:16:09 |       at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:357)
```

**Comment by peter-lawrey** [comment]
The problem here is that enum were being written using Java serialisation
making it very expensive when it should have been written as a string. This
was changed in the last release of java-lang to fix this but has created a
breaking change.
Roman can you revert the change and it will be fixed in a later, major
release.

**Comment by BoundedBuffer** [comment]
Seems it was an issue with binary-compat breaking, but so long ago, the binary format has changed.
