### ISSUE TITLE
MemoryLeaksTest fails on windows team city agent

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Map#140]
If there is a valid reason why this should fail on windows please change the test so that its not run on windows.

```
MemoryLeaksTest.testChronicleMapCollectedAndDirectMemoryReleased[0] 
(15) 06 Oct 17 16:21java.lang.AssertionError: expected:<1354368> but was:<1121856>     at org.junit.Assert.fail(Assert.java:88)     at org.junit.Assert.failNotEquals(Assert.java:834)     at org.junit.Assert.assertEquals(Assert.java:645)     at org.junit.Assert.assertEquals(Assert.java:631)     at net.openhft.chronicle.map.MemoryLeaksTest.testChronicleMapCollectedAndDirectMemoryReleased(MemoryLeaksTest.java:130)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)     at java.lang.reflect.Method.invoke(Method.java:498)     at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)     at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)     at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)     at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)     at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)     at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)     at org.junit.rules.RunRules.evaluate(RunRules.java:20)     at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)     at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)     at org.junit.runners.Suite.runChild(Suite.java:128)     at org.junit.runners.Suite.runChild(Suite.java:27)     at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)     at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)     at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)     at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)     at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)     at org.junit.runners.ParentRunner.run(ParentRunner.java:363)     at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)     at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)     at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)     at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)     at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)     at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)     ```

**Comment by peter-lawrey** [comment]
Memory allocation on windows is much slower than linux for some use cases.
This might be the cause of the problem if it is time sensitive.
ᐧ

**Comment by epickrram** [comment]
Added some debugging info, the test has passed 10+ times on windows. Going to have to wait for another failure...

**Comment by RobAustin** [comment]
I haven't seen any failure of this so closing
