### ISSUE TITLE
net.openhft.smoothie.Segment63 cannot be cast to net.openhft.smoothie.Segment

### ISSUE THREAD

**Issue by noahtaylor** [OpenHFT/Chronicle-Map#147]
I am getting the following exception when I am running a unit test.  Any ideas?

java.lang.ClassCastException: net.openhft.smoothie.Segment63 cannot be cast to net.openhft.smoothie.Segment
	at net.openhft.smoothie.SmoothieMap.makeSegment(SmoothieMap.java:589)
	at net.openhft.smoothie.SmoothieMap.initSegments(SmoothieMap.java:446)
	at net.openhft.smoothie.SmoothieMap.<init>(SmoothieMap.java:429)
	at net.openhft.smoothie.SmoothieMap.<init>(SmoothieMap.java:411)

**Comment by leventov** [comment]
I suspect some class loading issue. Could you try to build the library from source from the master here: https://github.com/leventov/SmoothieMap?

Also, this issue belongs to https://github.com/OpenHFT/SmoothieMap, not the Chronicle Map repo

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.271 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.271)

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.272 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.272)

**Comment by hft-team-city** [comment]
Released in Chronicle-Map-3.14.6 (https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.14.6), BOM-1.15.274 (https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-1.15.274)
