### ISSUE TITLE
IllegalStateException

### ISSUE THREAD

**Issue by AlexanderTyshchenko** [OpenHFT/Chronicle-Map#16]
Hi!
I've made stress testing ChronicleMap (2.0.22rc2) and got IllegalStateException

1) map size 10_000 tested 10_000 put/get/delete (40%/30%/30%)
2) map size 100_000 tested 100_000 put/get/delete (40%/30%/30%)
3) map size 1000_000 tested 1000_000 put/get/delete (40%/30%/30%)

Tested environment:
Windows 7 and Max OS X 10.10.1 (do not work for map size 10_000, for 100_000, 1_000_000, 10_000_00 is ok)
jdk1.8.25
```
public class ChronicleMapTest {
    public static void main(String[] args) throws IOException {
        int size = 10_000;

        byte[] array = new byte[1600];


        ChronicleMapBuilder<String, byte[]> builder = ChronicleMapBuilder.of(String.class, byte[].class).entries(size);
        ChronicleMap<String, byte[]> map = null;
        map = builder.createPersistedTo(new File("/work/openhft"));

        // for (int i = 0; i < size/2; i++)  -> the same problem
        for (int i = 0; i < size; i++) {
            map.put(String.valueOf(i+ ""), array);
        }

    }
}
```
What I did wrong?
```
java.lang.IllegalStateException: Segment is full or has no ranges of 51 continuous free chunks
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.alloc(VanillaChronicleMap.java:2012)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.putEntry(VanillaChronicleMap.java:1951)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.putWithoutLock(VanillaChronicleMap.java:1867)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.put3(VanillaChronicleMap.java:1820)
	at net.openhft.chronicle.map.VanillaChronicleMap.put2(VanillaChronicleMap.java:559)
	at net.openhft.chronicle.map.VanillaChronicleMap.put1(VanillaChronicleMap.java:544)
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:527)
```

And also need to add XStream dependency into project, because of
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/XStream
```

**Comment by BoundedBuffer** [comment]
The map is full :

- are you able to increase the number of entries you have
- are you writing fixed size entries
- are you setting the key size and values sizes ?


Rob

**Comment by hft-team-city** [comment]
sorry - I did not see you code example in the email, I did not see this example till I went to git.

**Comment by hft-team-city** [comment]
try this

{code}public static void main(String[] args) throws IOException {
        int size = 10_000;

        byte[] array = new byte[1600];


        ChronicleMapBuilder<String, byte[]> builder = ChronicleMapBuilder.of(String.class, byte[].class)
                .entries(size)
                .averageValueSize(1600);

        ChronicleMap<String, byte[]> map = null;
        map = builder.createPersistedTo(File.createTempFile("openhft", "dat"));

        for (int i = 0; i < size; i++) {
            map.put(String.valueOf(i + ""), array);
        }

        System.out.println("finished");
    }
{code}

**Comment by AlexanderTyshchenko** [comment]
Thanks very much!!! averageValueSize helped.

**Comment by peter-lawrey** [comment]
I suggest changing the key to suit the type you are using.

        ChronicleMap<Integer, byte[]> map = ChronicleMapBuilder
                .of(Integer.class, byte[].class)
                .entries(size)
                .averageValueSize(1600)
                .createPersistedTo(File.createTempFile("openhft", "dat"));

        for (int i = 0; i < size; i++) {
            map.put(i, array);
        }

**Comment by zhuyoulong** [comment]
**I reported the exception is as follows:**
Caused by: java.lang.IllegalStateException: Segment is full or has no ranges of 13 continuous free chunks
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.alloc(VanillaChronicleMap.java:2437)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.putEntry(VanillaChronicleMap.java:2376)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.putWithoutLock(VanillaChronicleMap.java:2289)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.put3(VanillaChronicleMap.java:2241)
	at net.openhft.chronicle.map.VanillaChronicleMap.put2(VanillaChronicleMap.java:613)

This problem may be related to the capacity you have to say
I would like to ask entries can automatically expand, rather than the size of the fixed file?
Or do you think the next version of the document automatic expansion?

**Comment by leventov** [comment]
@zhuyoulong in Chronicle Map 3 this problem has gone away. Also I suggest to try to use `averageValue()` instead of `averageValueSize()`, because your assumptions about "value size" might be wrong.
