### ISSUE TITLE
Storing Integers as values

### ISSUE THREAD

**Issue by jackmalkovick** [OpenHFT/Chronicle-Map#180]
We are trying to insert (String, Integer) values in a Chornicle map.
We of course did not configure an avgValueSize().

It seems we get an error because chronicle tries to write on 2 bytes the Integer 4 byte value.

```
java.lang.IllegalArgumentException: sizeToWrite: 2, constant size should be: 4
	at net.openhft.chronicle.hash.serialization.impl.ConstantSizeMarshaller.writeSize(ConstantSizeMarshaller.java:64) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initValueSize(CompiledMapQueryContext.java:3262) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initValue(CompiledMapQueryContext.java:3319) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.putEntry(CompiledMapQueryContext.java:3995) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.doInsert(CompiledMapQueryContext.java:4183) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.MapEntryOperations.insert(MapEntryOperations.java:153) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.insert(CompiledMapQueryContext.java:4106) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.MapMethods.put(MapMethods.java:88) ~[chronicle-map-3.17.1.jar:3.17.1]
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:712) ~[chronicle-map-3.17.1.jar:3.17.1]
```

**Comment by dpisklov** [comment]
Would you be able to provide a failing test case here to see how you create/interact with the map?

**Comment by jackmalkovick** [comment]
Uh... it was because of my custom marshaller. I thought that Chronicle will go around it for known types.
I have a marshaller for Serializables. 
Can I configure Chronicle to use my marshaller, but prohibit him from checking the constant size for known Integer type?

**Comment by RobAustin** [comment]
no - if you provided your marshaller it will use that.

**Comment by dpisklov** [comment]
Can I ask why you want to use custom marshaller for Integer?

**Comment by jackmalkovick** [comment]
The marshaller is used for Serializable and uses FSTObjectOutput to write objects. It was the one who "compressed" the Integer. Of course I did not intend to used it for Integer classes.
If I'm forced to use my marshaller for Integer also, why can't I specify a different value size than the fixed 4 bytes?

**Comment by dpisklov** [comment]
First of all, why are you forced to use your marshaller for Integer? If your map is String -> Integer I would suggest you not to specify the value marshaller at all and default will be used.
Secondly, if you still want to do that, likely your marshaller reports incorrect size. Your marshaller should be implementing the following interface:

```
public interface SizedWriter<T> extends Marshallable {
    long size(@NotNull T toWrite);

    void write(Bytes out, long size, @NotNull T toWrite);
}
```

My guess is that size() method implementaion in your custom  marshaller returns 4 for integer

**Comment by jackmalkovick** [comment]
You are right. Thank you for your advice!

**Comment by dpisklov** [comment]
No problem
