### ISSUE TITLE
java.lang.IllegalMonitorStateException: Expected update lock

### ISSUE THREAD

**Issue by sarkissow** [OpenHFT/Chronicle-Map#188]
I'm getting the exception when trying to call compute method on a same file from multiple processes. 
Anything wrong with the way I'm doing that?

<pre>
public class ChronicleTest {

    public static void main(String[] args) throws IOException {
        ChronicleMapBuilder<String, Long> builder =
                ChronicleMapBuilder.of(String.class, Long.class)
                        .name("test")
                        .averageKeySize(5)
                        .entries(1);

        ChronicleMap<String, Long> map = builder.createOrRecoverPersistedTo(new File("test.chronicle"));

        Long compute = map.compute("testKey", (k, v) -> {
            // set a breakpoint here and run multiple instances
            return v == null ? 0 : v + 1;
        });
        System.out.println("result = " + compute);
    }
}
</pre>

<pre>
Exception in thread "main" java.lang.IllegalMonitorStateException: Expected update lock
	at net.openhft.chronicle.algo.locks.VanillaReadWriteUpdateWithWaitsLockingStrategy.checkUpdateLocked(VanillaReadWriteUpdateWithWaitsLockingStrategy.java:98)
	at net.openhft.chronicle.algo.locks.VanillaReadWriteUpdateWithWaitsLockingStrategy.tryUpgradeUpdateToWriteLock(VanillaReadWriteUpdateWithWaitsLockingStrategy.java:265)
	at net.openhft.chronicle.hash.impl.BigSegmentHeader.innerTryUpgradeUpdateToWriteLock(BigSegmentHeader.java:278)
	at net.openhft.chronicle.hash.impl.BigSegmentHeader.upgradeUpdateToWriteLock(BigSegmentHeader.java:493)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext$WriteLock.lock(CompiledMapQueryContext.java:1744)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.innerDefaultReplaceValue(CompiledMapQueryContext.java:4256)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.doReplaceValue(CompiledMapQueryContext.java:4268)
	at net.openhft.chronicle.map.MapEntryOperations.replaceValue(MapEntryOperations.java:136)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.replaceValue(CompiledMapQueryContext.java:4042)
	at net.openhft.chronicle.map.MapMethods.compute(MapMethods.java:345)
	at net.openhft.chronicle.map.VanillaChronicleMap.compute(VanillaChronicleMap.java:740)
	at ChronicleTest.main(ChronicleTest.java:18)
</pre>

**Comment by sarkissow** [comment]
Ah, I guess createOrRecoverPersistedTo is the source of the trouble? Am I expected to use createPersistedTo for this purpose?
