### ISSUE TITLE
IllegalMonitorStateException reading from ChronicleMap

### ISSUE THREAD

**Issue by uberbrodt** [OpenHFT/Chronicle-Map#20]
Hi, I have a rather large map (4.8GB serialized in memory mapped file, ~8M entries) that I'm using in a Scala/Akka project. At one point I have a parallelized search (~200 Actors) that are pulling values out of the map and performing a distance calculation. I'm seeing slow response times and the following errors:

Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by processId: 134217729, threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by processId: 134217729, threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by threadId: 0
Grabbing lock held by processId: 134217728, threadId: 0
Grabbing lock held by threadId: 0
Failed to unlock as expected
java.lang.IllegalMonitorStateException: writersLock underflow 0
	at net.openhft.lang.io.AbstractBytes.unlockRWWriteLock(AbstractBytes.java:2800) ~[lang-6.6.1.jar:na]
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.readUnlock(VanillaChronicleMap.java:1649) [chronicle-map-2.1.4.jar:2.1.4]
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.acquire(VanillaChronicleMap.java:1731) [chronicle-map-2.1.4.jar:2.1.4]
	at net.openhft.chronicle.map.VanillaChronicleMap.lookupUsing(VanillaChronicleMap.java:639) [chronicle-map-2.1.4.jar:2.1.4]
	at net.openhft.chronicle.map.VanillaChronicleMap.lookupUsing(VanillaChronicleMap.java:625) [chronicle-map-2.1.4.jar:2.1.4]
	at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:576) [chronicle-map-2.1.4.jar:2.1.4]
	at net.uberbrodt.idistance.SearchCluster$$anonfun$qualityFilterList$1.apply(SearchCluster.scala:38) [classes/:na]
	at net.uberbrodt.idistance.SearchCluster$$anonfun$qualityFilterList$1.apply(SearchCluster.scala:37) [classes/:na]
	at scala.collection.immutable.List.map(List.scala:277) [scala-library-2.11.6.jar:na]
	at net.uberbrodt.idistance.SearchCluster.qualityFilterList(SearchCluster.scala:37) [classes/:na]
	at net.uberbrodt.idistance.SearchCluster.findNearestNeighbors(SearchCluster.scala:107) [classes/:na]
	at net.uberbrodt.idistance.SearchCluster$$anonfun$receive$1.applyOrElse(SearchCluster.scala:24) [classes/:na]
	at akka.actor.Actor$class.aroundReceive(Actor.scala:465) [akka-actor_2.11-2.3.9.jar:na]
	at net.uberbrodt.idistance.SearchCluster.aroundReceive(SearchCluster.scala:17) [classes/:na]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:516) [akka-actor_2.11-2.3.9.jar:na]
	at akka.actor.ActorCell.invoke(ActorCell.scala:487) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:254) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.run(Mailbox.scala:221) [akka-actor_2.11-2.3.9.jar:na]
	at akka.dispatch.Mailbox.exec(Mailbox.scala:231) [akka-actor_2.11-2.3.9.jar:na]
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979) [scala-library-2.11.6.jar:na]
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107) [scala-library-2.11.6.jar:na]
Failed to unlock as expected

The project completes, but I'm not sure what the errors mean. Too much parallelism? Map too large? I'll work on creating a test project that can be used to replicate the issue if necessary.

**Comment by leventov** [comment]
Could you please show the code using Chronicle Map (in the "quality filter", as far as I understand).

**Comment by uberbrodt** [comment]
Sure:
```scala
  def qualityFilter(queryNode: Assessment, node:IndexNode): Future[IndexNode] = {
    Future { val a = Assessment.assessmentMap.get(node.label)
      val distance = Distance.calculateDistance(queryNode, a)
      IndexNode(distance, node.label)
    }
  }
````

Here's the map definition:

```scala
object Assessment {

  val assessmentMap = initalizeAssessmentsChronicleMap

  def initalizeAssessmentsChronicleMap:ChronicleMap[String, Assessment] = {
    //    val tmp = System.getProperty("java.io.tmpdir");
    val tmp = "/tmp"
    val pathname = tmp + "/8m/assessments.dat";
    val file = new File(pathname)

    val mapBuilder = ChronicleMapBuilder.of(classOf[String],classOf[Assessment]).entries(9000000l)
      .constantKeySizeBySample("d0058f7c-275f-4023-a01f-6e463c2bd459")
      .constantValueSizeBySample(Assessment.findByAssessmentId("d0058f7c-275f-4023-a01f-6e463c2bd459"))

    mapBuilder.createPersistedTo(file)
  }
```

**Comment by peter-lawrey** [comment]
It is expected that any lock should be held only briefly. This means no
blocking IO operations or long running tasks. You should copy what you need
for any access to the map.

**Comment by soid** [comment]
Hi Peter, can you please explain more on this? If we get an element from the map, are you saying there's a lock on the element that prevents getting the same element from the map, and we need to clone the element if we hold the object for some time?

My stacktrace is slightly different during the VanillaChronicleMap.containsKey() call
```
java.lang.IllegalStateException: writersWaiting has underflowed
at net.openhft.lang.io.AbstractBytes.tryRWWriteLock0(AbstractBytes.java:2770)
at net.openhft.lang.io.AbstractBytes.tryRWWriteLock(AbstractBytes.java:2735)
at net.openhft.chronicle.map.VanillaChronicleMap$Segment.readLock(VanillaChronicleMap.java:1572)
at net.openhft.chronicle.map.VanillaChronicleMap$Segment.containsKey(VanillaChronicleMap.java:2226)
at net.openhft.chronicle.map.VanillaChronicleMap$Segment.access$000(VanillaChronicleMap.java:1442)
at net.openhft.chronicle.map.VanillaChronicleMap.containsKey(VanillaChronicleMap.java:908)
at net.openhft.chronicle.map.VanillaChronicleMap.containsKey(VanillaChronicleMap.java:887)
```

I may hold an object for about 200 microseconds what under high load may raise the issue.

**Comment by peter-lawrey** [comment]
This is more a symptom than the cause. It means that the lock was grabbed
while this thread was holding it. The real cause is; why is the system
stalling long enough that the lock is being grabbed. The default lock time
out is many seconds.
