### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: net.openhft.chronicle.core.values.LongValue$$Heap

### ISSUE THREAD

**Issue by wangfajun** [OpenHFT/Chronicle-Map#206]
<dependency>
   <groupId>net.openhft</groupId>
   <artifactId>chronicle-map</artifactId>
   <version>3.17.8</version>
</dependency>

Then have following "application" main class: 

@SpringBootApplication
@EnableAutoConfiguration
public class Application {
    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);

        LongValue key = Values.newHeapInstance(LongValue.class);

    }
}

Windos works well,Linux doesn't

Linux:  Running Application will result in following Exception:

/net/openhft/chronicle/core/values/LongValue$$Heap.java:13: error: cannot find symbol
import net.openhft.chronicle.core.Jvm;
                                 ^
  symbol:   class Jvm
  location: package net.openhft.chronicle.core
/net/openhft/chronicle/core/values/LongValue$$Heap.java:24: error: cannot find symbol
      Field theUnsafe = Jvm.getField(Unsafe.class, "theUnsafe");
                        ^
  symbol:   variable Jvm
  location: class net.openhft.chronicle.core.values.LongValue$$Heap
/net/openhft/chronicle/core/values/LongValue$$Heap.java:26: error: cannot find symbol
      valueOffset = UNSAFE.objectFieldOffset(Jvm.getField(LongValue$$Heap.class, "__fieldvalue"));
                                             ^
  symbol:   variable Jvm
  location: class net.openhft.chronicle.core.values.LongValue$$Heap
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: net.openhft.chronicle.values.ImplGenerationFailedException: java.lang.ClassNotFoundException: net.openhft.chronicle.core.values.LongValue$$Heap
	at net.openhft.chronicle.values.ValueModel.createClass(ValueModel.java:325)
	at net.openhft.chronicle.values.ValueModel.createHeapClass(ValueModel.java:307)
	at net.openhft.chronicle.values.ValueModel.heapClass(ValueModel.java:297)
	at net.openhft.chronicle.values.Values.heapClassFor(Values.java:71)
	at net.openhft.chronicle.values.Values.newHeapInstance(Values.java:40)
	at com.cloudwalk.jvmtest.Application.main(Application.java:16)
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.openhft.chronicle.core.values.LongValue$$Heap
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.openhft.chronicle.values.CachedCompiler.loadFromJava(CachedCompiler.java:99)
	at net.openhft.chronicle.values.ValueModel.createClass(ValueModel.java:323)
	... 13 more

**Comment by dpisklov** [comment]
@wangfajun you have some classpath issues, check your maven dependencies. Jvm class is from the chronicle-core project which is direct dependency of chronicle-map.
