### ISSUE TITLE
Exception when running on a system where the "noexec" attribute is set for /tmp

### ISSUE THREAD

**Issue by richschaaf** [OpenHFT/Chronicle-Map#221]
Hi all,

When I run my ChronicleMap application, it throws an exception (see below for the back trace).

If I change the /tmp file system to remove the "noexec" attribute, the application works.

Is there a way to configure (for example, through the ChronicleMap API or through environment variables) where the jna objects are created?

My environment:
- Ubuntu 18.04
- OpenJDK 11
- ChronicleMap 3.19.4
- jna package 4.5.2

``
Exception in thread "pool-2-thread-1" java.lang.UnsatisfiedLinkError: /tmp/jna--868129468/jna2708647627236688750.tmp: /tmp/jna--868129468/jna2708647627236688750.tmp: failed to map segment from shared object
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1834)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:947)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:922)
        at com.sun.jna.Native.<clinit>(Native.java:190)
        at net.openhft.chronicle.hash.impl.util.jna.PosixFallocate.<clinit>(PosixFallocate.java:18)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.map(VanillaChronicleHash.java:987)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createMappedStoreAndSegments(VanillaChronicleHash.java:491)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1820)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1724)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1618)
``

Kind regards,
Rich

**Comment by dpisklov** [comment]
This is a well-known issue related to JNA library (that is, it's not Chronicle Map, or the Chronicle stack as a whole, issue). A few links:
* [one](https://support.cloudbees.com/hc/en-us/articles/218233908-Unable-to-start-Jenkins-due-to-tmp-directory-mounted-with-noexec-option)
* [two](https://support.cloudbees.com/hc/en-us/articles/215281717-Jenkins-fails-to-start-with-JNA-error)
* [three](https://github.com/elastic/elasticsearch/issues/18272)

All of them suggest either remove noexec from the /tmp, or alternatively you can set -Djava.io.tmpdir to some directory that won't have noexec.
