### ISSUE TITLE
java.lang.IllegalArgumentException: Mapping more than 4096 MiB is unusable on Windows,

### ISSUE THREAD

**Issue by MichaelBagley** [OpenHFT/Chronicle-Map#234]
I am currently running    3.20.61 on windows 10 x64 professional.  I am using the following to build my map:

       ChronicleMapBuilder<String, String> builder = ChronicleMap.of(String.class, String.class)
                .name("tjc by " + algorithm + " map")
                .entries(lineCount)
                .averageValue("20150701:20180630=1234=900:1098:E=9520;20150701:20180630=900:1098:E=9520;20150701:20180630=900:1098:E=9520;")
                .averageKey("252:KNOXVILLE:37917:BLUFF ST")
                .maxBloatFactor(1.5);

My lineCount is approximately 6.2M

I have a 24G machine, and I am invoking java with Xmx10g.  I have other maps in the <4G range.  What options do I have to prevent this exception on Windows.

**Comment by dpisklov** [comment]
Stacktrace please?

**Comment by MichaelBagley** [comment]
Legend:  module:initSstZip9 source:../ng-tjc-content/source/nonsst//Zip4.dat destination:..\ng-tjc-content\object\nonsst\20200922202225//chronicle-map-zip9.dat
java.lang.IllegalArgumentException: Mapping more than 4096 MiB is unusable on Windows, size = 4133 MiB
        at net.openhft.chronicle.core.OS.map(OS.java:341)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.map(VanillaChronicleHash.java:1039)
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createMappedStoreAndSegments(VanillaChronicleHash.java:507)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1782)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1685)
        at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1545)
        at com.sovos.tjc.service.ChronicleMapService.initPersistedFile(ChronicleMapService.java:318)
        at com.sovos.tjc.service.ChronicleMapService.initSstAddress(ChronicleMapService.java:538)
        at com.sovos.tjc.service.ChronicleMapService.lambda$8(ChronicleMapService.java:198)
        at com.sovos.tjc.service.ChronicleMapService.lambda$22(ChronicleMapService.java:260)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by dpisklov** [comment]
OK [here's](https://bugs.java.com/bugdatabase/view_bug.do%3Fbug_id%3D6776490) the reason for this. Quoting:
>  This is a symptom of Windows memory management and is not solvable in the JDK.

The two options you have are either use less than 4Gb or don't use Linux (I would strongly suggest latter).

**Comment by MichaelBagley** [comment]
Understood.  Thank you for your time.

**Comment by MichaelBagley** [comment]
I presume you meant don't use Windows

**Comment by dpisklov** [comment]
Yes - fixed :D
