### ISSUE TITLE
fixed msync on mac

### ISSUE THREAD

**Issue by RobAustin** [OpenHFT/Chronicle-Map#304]
msync is not working on mac 

```
java.lang.UnsatisfiedLinkError: 
/Users/teamcity/Library/Caches/JNA/temp/jna2495370899506262640.tmp: dlopen(/Users/teamcity/Library/Caches/JNA/temp/jna2495370899506262640.tmp, 1): no suitable image found.  Did find:
	/Users/teamcity/Library/Caches/JNA/temp/jna2495370899506262640.tmp: no matching architecture in universal wrapper
	/Users/teamcity/Library/Caches/JNA/temp/jna2495370899506262640.tmp: no matching architecture in universal wrapper
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1018)
	at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:988)
	at com.sun.jna.Native.<clinit>(Native.java:195)
	at com.sun.jna.NativeLibrary.<clinit>(NativeLibrary.java:87)
	at net.openhft.chronicle.hash.impl.util.jna.PosixMsync.<clinit>(PosixMsync.java:28)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:911)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.msync(VanillaChronicleHash.java:897)
	at net.openhft.chronicle.map.ChronicleMapBuilder.commitChronicleMapReady(ChronicleMapBuilder.java:406)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1826)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1721)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1566)
	at net.openhft.lang.values.ArrayTest.test0(ArrayTest.java:46)

```

**Comment by JerryShea** [comment]
Fixed by https://github.com/OpenHFT/Chronicle-Map/commit/acdc54a4b8c2a10868ed3625942ceaf82c029703
