### ISSUE TITLE
IllegalStateException during entry removal causing later errors on recovery

### ISSUE THREAD

**Issue by alamar** [OpenHFT/Chronicle-Map#311]
```
java.lang.IllegalStateException: ChronicleMap{...}: We a tier without interruption, but according to tier counters there should be 1 more entries. Size diverged?
        at net.openhft.chronicle.map.impl.CompiledReplicatedMapIterationContext.forEachTierEntryWhile(CompiledReplicatedMapIterationContext.java:4457)
        at net.openhft.chronicle.map.impl.CompiledReplicatedMapIterationContext.innerForEachSegmentEntryWhile(CompiledReplicatedMapIterationContext.java:4469)
        at net.openhft.chronicle.map.impl.CompiledReplicatedMapIterationContext.forEachSegmentEntryWhile(CompiledReplicatedMapIterationContext.java:4491)
        at net.openhft.chronicle.map.impl.CompiledReplicatedMapIterationContext.forEachSegmentEntry(CompiledReplicatedMapIterationContext.java:4497)
        at net.openhft.chronicle.map.ChronicleMapIterator.fillEntryBuffer(ChronicleMapIterator.java:60)
        at net.openhft.chronicle.map.ChronicleMapIterator.hasNext(ChronicleMapIterator.java:76)
```

This is when doing a scan/conditional map.remove() in a loop.

Later, after restart, the following errors are seen:
```ChronicleMap - entries with duplicate key ... in segment 3911
Wrong number of entries counter for tier with index 3912, stored: 4563, should be: 456
```

The map will be able to recover after a large number of such messages.

**Comment by minborg** [comment]
Is this related to the problems we fixed in the CRMIC last autumn? Can we close this now @alamar ?

**Comment by alamar** [comment]
I'm not sure, can you point me to the fix @minborg ?

**Comment by minborg** [comment]
Here it is @alamar https://github.com/ChronicleEnterprise/Chronicle-Map-Enterprise/issues/64

**Comment by alamar** [comment]
I didn't think this issue for some time, marking as closed.
