### ISSUE TITLE
Failure to acquire lock on allocating a new tier in combination with acquireContext

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Map#376]
Apparently, the same lock might be acquired by `acquireContext()` and `VanillaChronicleHash.allocateTier()` and because the lock is not reentrant, it fails when allocating a new tier. 

See `WordCountTest`

```
java.lang.IllegalStateException: Failed to acquire the lock
  at net.openhft.chronicle.algo.locks.AcquisitionStrategies$SpinLoopOrFailAcquisitionStrategy.end(AcquisitionStrategies.java:89)
  at net.openhft.chronicle.algo.locks.AcquisitionStrategies$SpinLoopAcquisitionStrategy.acquire(AcquisitionStrategies.java:66)
  at net.openhft.chronicle.hash.impl.VanillaChronicleHash.globalMutableStateLock(VanillaChronicleHash.java:788)
  at net.openhft.chronicle.hash.impl.VanillaChronicleHash.allocateTier(VanillaChronicleHash.java:821)
  at net.openhft.chronicle.map.impl.CompiledMapQueryContext.nextTier(CompiledMapQueryContext.java:3121)
  at net.openhft.chronicle.map.impl.CompiledMapQueryContext.alloc(CompiledMapQueryContext.java:3482)
  at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initEntryAndKey(CompiledMapQueryContext.java:3500)
  at net.openhft.chronicle.map.impl.CompiledMapQueryContext.putEntry(CompiledMapQueryContext.java:3993)
  at net.openhft.chronicle.map.impl.CompiledMapQueryContext.doInsert(CompiledMapQueryContext.java:4182)
  at net.openhft.chronicle.map.MapEntryOperations.insert(MapEntryOperations.java:153)
  at net.openhft.chronicle.map.impl.CompiledMapQueryContext.insert(CompiledMapQueryContext.java:4105)
  at net.openhft.chronicle.map.MapMethods.acquireUsing(MapMethods.java:155)
  at net.openhft.chronicle.map.VanillaChronicleMap.acquireUsingBody(VanillaChronicleMap.java:815)
  at net.openhft.chronicle.map.VanillaChronicleMap.acquireContext(VanillaChronicleMap.java:357)
  at net.openhft.chronicle.map.VanillaChronicleMap.acquireContext(VanillaChronicleMap.java:61)
  at eg.WordCountTest.wordCountTest(WordCountTest.java:62)
  ```

**Comment by JerryShea** [comment]
Closing as I believe this has been fixed

**Comment by francescopeloi** [comment]
hi there, I am experiencing the same:

```
java.lang.IllegalStateException: Failed to acquire the lock
	at net.openhft.chronicle.algo.locks.AcquisitionStrategies$SpinLoopOrFailAcquisitionStrategy.end(AcquisitionStrategies.java:89)
	at net.openhft.chronicle.algo.locks.AcquisitionStrategies$SpinLoopAcquisitionStrategy.acquire(AcquisitionStrategies.java:66)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.globalMutableStateLock(VanillaChronicleHash.java:819)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.allocateTier(VanillaChronicleHash.java:867)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.nextTier(CompiledMapQueryContext.java:3119)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.alloc(CompiledMapQueryContext.java:3480)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initEntryAndKey(CompiledMapQueryContext.java:3498)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.putEntry(CompiledMapQueryContext.java:3991)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.doInsert(CompiledMapQueryContext.java:4180)
	at net.openhft.chronicle.map.MapEntryOperations.insert(MapEntryOperations.java:153)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.insert(CompiledMapQueryContext.java:4103)
	at net.openhft.chronicle.map.MapMethods.put(MapMethods.java:86)
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:919)
	at ...mycode...
```

I will try to create a unit test but this is happening consistently on a 512GB RAM machine, so even if I reproduce it with a unit test, I guess it's going to be hard for people to run?
