### ISSUE TITLE
Deflake CHMUseCasesTest

### ISSUE THREAD

**Issue by minborg** [OpenHFT/Chronicle-Map#385]
https://teamcity.chronicle.software/buildConfiguration/OpenHFT_BuildAll_BuildJava8compileJava8/643627?buildTab=overview&showRootCauses=false&expandBuildProblemsSection=true&expandBuildTestsSection=true

```
java.lang.AssertionError: expected null, but was:<java.nio.HeapByteBuffer[pos=0 lim=2 cap=2]>
  at org.junit.Assert.fail(Assert.java:89)
  at org.junit.Assert.failNotNull(Assert.java:756)
  at org.junit.Assert.assertNull(Assert.java:738)
  at org.junit.Assert.assertNull(Assert.java:748)
  at net.openhft.chronicle.map.CHMUseCasesTest.testByteBufferDirectByteBufferMap(CHMUseCasesTest.java:1224)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)


// Caused by the very first operation invoked on a new map
assertNull(map.put(key1, value1));

```

**Comment by hft-team-city** [comment]
Released in [Chronicle-Map-3.23ea0](https://github.com/OpenHFT/Chronicle-Map/releases/chronicle-map-3.23ea0), [BOM-2.22.129](https://github.com/OpenHFT/OpenHFT/releases/chronicle-bom-2.22.129)
