### ISSUE TITLE
Chronicle-Map Oracle JDK 11 Support Issue

### ISSUE THREAD

**Issue by isharawijesinghe** [OpenHFT/Chronicle-Map#390]
Chronicle-Maps has used "jdk.internal.ref.Cleaner" in their latest releases, while oracle JDK 11 supports "java.lang.ref.Cleaner" (https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8149925) . This causing JDK 11 upgrade issue

**Comment by isharawijesinghe** [comment]
`Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: jdk.internal.ref.Cleaner from [Module "deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear" from Service Module Loader]
    at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.hash.impl.util.CleanerUtils.<clinit>(CleanerUtils.java:42)
    ... 63 more
Caused by: java.lang.ClassNotFoundException: jdk.internal.ref.Cleaner from [Module "deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear" from Service Module Loader]
    at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
    at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
    at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
    at java.base/java.lang.Class.forName0(Native Method)
    at java.base/java.lang.Class.forName(Class.java:315)
    at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.hash.impl.util.CleanerUtils.<clinit>(CleanerUtils.java:35)
    ... 63 more
`


An above exception might be useful

**Comment by JerryShea** [comment]
hi @isharawijesinghe, Chronicle Map is supported on Java 11.

If you look at `net.openhft.chronicle.hash.impl.util.CleanerUtils` you will see it takes account of JVM version to resolve the cleaner class. Can you debug in to https://github.com/OpenHFT/Chronicle-Map/blob/23597364ba9b6c48055ba5fdbb5403d64d9f5dc1/src/main/java/net/openhft/chronicle/hash/impl/util/CleanerUtils.java#L33 to see why it is getting the wrong result?

**Comment by JerryShea** [comment]
Chronicle Map is supported on Java 11 - please try with command line args as per https://chronicle.software/chronicle-support-java-17/ and if you still see a problem please re-open!

**Comment by isharawijesinghe** [comment]
Tried the above workaround but the problem still persists. I have passed the `following` JVM parameters

`JAVA_OPTS: "-Dprogram.name=standalone.bat -Xms64M -Xmx512M -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true 
-Djboss.modules.system.pkgs=org.jboss.byteman --add-exports=java.base/jdk.internal.ref=ALL-UNNAMED 
--add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED 
--add-exports=jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-opens=jdk.compiler/com.sun.tools.javac=ALL-UNNAMED 
--add-opens=java.base/java.lang=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.io=ALL-UNN`


The log will be attached her
[server.log](https://github.com/OpenHFT/Chronicle-Map/files/7929979/server.log)

**Comment by isharawijesinghe** [comment]
Plus here exception is not `In accessible exception`, so exporting will not help. But the problem is `java.lang.ClassNotFoundException` due to JDK crrently replaced `java.lang.ref.Cleaner` instead of `jdk.internal.ref.Cleaner`

**Comment by isharawijesinghe** [comment]
In case if it is helpful i will paste exception here as well

`2022-01-25 07:06:58,774 ERROR [stderr] (ServerService Thread Pool -- 75) net.openhft.chronicle.core.Jvm: Unable to determine max direct memory

2022-01-25 07:06:59,030 ERROR [net.openhft.chronicle.hash.impl.util.CleanerUtils] (ServerService Thread Pool -- 75) Unable to initialise CleanerUtils: java.lang.ClassNotFoundException: jdk.internal.ref.Cleaner from [Module "deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.hash.impl.util.CleanerUtils.<clinit>(CleanerUtils.java:35)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.hash.impl.VanillaChronicleHash.registerCleaner(VanillaChronicleHash.java:479)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.prepareMapPublication(ChronicleMapBuilder.java:1749)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1727)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.recoverPersistedTo(ChronicleMapBuilder.java:1651)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1634)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1625)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1619)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.ChronicleCommonUtils.createChronicleMap(ChronicleCommonUtils.java:27)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.persist.MemMapHandlerCore.createChronicle(MemMapHandlerCore.java:93)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.persist.MemMapHandlerCore.initMemMapFile(MemMapHandlerCore.java:114)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.persist.MemMapHandlerCore.init(MemMapHandlerCore.java:65)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Bootstrapper.jar//com.dfn.oms.newgen.core.bootstrap.OMSInitCore.initMemMapPersists(OMSInitCore.java:281)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Bootstrapper.jar//com.dfn.oms.newgen.core.bootstrap.BootstrapCoreBean.initialize(BootstrapCoreBean.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.as.ee//org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptor.java:96)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld.common//org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doLifecycleInterception(Jsr299BindingsInterceptor.java:122)
	at org.jboss.as.weld.common//org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:111)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.core//org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.as.weld.common//org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:53)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee//org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.interceptors.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:105)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee//org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:264)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.notSupported(LifecycleCMTTxInterceptor.java:110)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:70)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee//org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.singleton.StartupCountDownInterceptor.processInvocation(StartupCountDownInterceptor.java:25)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161)
	at org.jboss.as.ee//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:134)
	at org.jboss.as.ee//org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:124)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:138)
	at org.jboss.as.ee//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads//org.jboss.threads.JBossThread.run(JBossThread.java:320)

2022-01-25 07:06:59,039 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 75) MSC000001: Failed to start service jboss.deployment.subunit."DFNNTPOMS_X_X_3.003.000.00.0.ear"."Bootstrapper.jar".component.BootstrapCoreBean.START: org.jboss.msc.service.StartException in service jboss.deployment.subunit."DFNNTPOMS_X_X_3.003.000.00.0.ear"."Bootstrapper.jar".component.BootstrapCoreBean.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
	at org.jboss.as.ee//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:57)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads//org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
	at org.jboss.as.ee//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:163)
	at org.jboss.as.ee//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:134)
	at org.jboss.as.ee//org.jboss.as.ee.component.BasicComponent.createInstance(BasicComponent.java:88)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.singleton.SingletonComponent.getComponentInstance(SingletonComponent.java:124)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.singleton.SingletonComponent.start(SingletonComponent.java:138)
	at org.jboss.as.ee//org.jboss.as.ee.component.ComponentStartService$1.run(ComponentStartService.java:54)
	... 6 more
Caused by: javax.ejb.EJBException: WFLYEJB0442: Unexpected Error
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.CMTTxInterceptor.handleExceptionInNoTx(CMTTxInterceptor.java:211)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:266)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.notSupported(LifecycleCMTTxInterceptor.java:110)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.LifecycleCMTTxInterceptor.processInvocation(LifecycleCMTTxInterceptor.java:70)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.injection.WeldInjectionContextInterceptor.processInvocation(WeldInjectionContextInterceptor.java:43)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee//org.jboss.as.ee.concurrent.ConcurrentContextInterceptor.processInvocation(ConcurrentContextInterceptor.java:45)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation//org.jboss.invocation.ContextClassLoaderInterceptor.processInvocation(ContextClassLoaderInterceptor.java:60)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.component.singleton.StartupCountDownInterceptor.processInvocation(StartupCountDownInterceptor.java:25)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation//org.jboss.invocation.ChainedInterceptor.processInvocation(ChainedInterceptor.java:53)
	at org.jboss.as.ee//org.jboss.as.ee.component.BasicComponent.constructComponentInstance(BasicComponent.java:161)
	... 11 more
Caused by: java.lang.ExceptionInInitializerError
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.hash.impl.VanillaChronicleHash.registerCleaner(VanillaChronicleHash.java:479)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.prepareMapPublication(ChronicleMapBuilder.java:1749)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1727)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.recoverPersistedTo(ChronicleMapBuilder.java:1651)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1634)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1625)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1619)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.ChronicleCommonUtils.createChronicleMap(ChronicleCommonUtils.java:27)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.persist.MemMapHandlerCore.createChronicle(MemMapHandlerCore.java:93)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.persist.MemMapHandlerCore.initMemMapFile(MemMapHandlerCore.java:114)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Utility.jar//com.dfn.oms.newgen.core.utility.chronicle.persist.MemMapHandlerCore.init(MemMapHandlerCore.java:65)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Bootstrapper.jar//com.dfn.oms.newgen.core.bootstrap.OMSInitCore.initMemMapPersists(OMSInitCore.java:281)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear.Bootstrapper.jar//com.dfn.oms.newgen.core.bootstrap.BootstrapCoreBean.initialize(BootstrapCoreBean.java:66)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.as.ee//org.jboss.as.ee.component.ManagedReferenceLifecycleMethodInterceptor.processInvocation(ManagedReferenceLifecycleMethodInterceptor.java:96)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld.common//org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.doLifecycleInterception(Jsr299BindingsInterceptor.java:122)
	at org.jboss.as.weld.common//org.jboss.as.weld.interceptors.Jsr299BindingsInterceptor.processInvocation(Jsr299BindingsInterceptor.java:111)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext$Invocation.proceed(InterceptorContext.java:509)
	at org.jboss.weld.core//org.jboss.weld.ejb.AbstractEJBRequestScopeActivationInterceptor.aroundInvoke(AbstractEJBRequestScopeActivationInterceptor.java:73)
	at org.jboss.as.weld.common//org.jboss.as.weld.ejb.EjbRequestScopeActivationInterceptor.processInvocation(EjbRequestScopeActivationInterceptor.java:89)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.injection.WeldInjectionInterceptor.processInvocation(WeldInjectionInterceptor.java:53)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee//org.jboss.as.ee.component.AroundConstructInterceptorFactory$1.processInvocation(AroundConstructInterceptorFactory.java:28)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.injection.WeldInterceptorInjectionInterceptor.processInvocation(WeldInterceptorInjectionInterceptor.java:56)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.weld//org.jboss.as.weld.interceptors.Jsr299BindingsCreateInterceptor.processInvocation(Jsr299BindingsCreateInterceptor.java:105)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ee//org.jboss.as.ee.component.NamespaceContextInterceptor.processInvocation(NamespaceContextInterceptor.java:50)
	at org.jboss.invocation//org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:422)
	at org.jboss.as.ejb3//org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInNoTx(CMTTxInterceptor.java:264)
	... 26 more
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: jdk.internal.ref.Cleaner from [Module "deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear" from Service Module Loader]
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.hash.impl.util.CleanerUtils.<clinit>(CleanerUtils.java:42)
	... 63 more
Caused by: java.lang.ClassNotFoundException: jdk.internal.ref.Cleaner from [Module "deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:198)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:412)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:400)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:315)
	at deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear//net.openhft.chronicle.hash.impl.util.CleanerUtils.<clinit>(CleanerUtils.java:35)
	... 63 more

2022-01-25 07:06:59,053 ERROR [org.jboss.as.controller.management-operation] (Controller Boot Thread) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "DFNNTPOMS_X_X_3.003.000.00.0.ear")]) - failure description: {"WFLYCTL0080: Failed services" => {"jboss.deployment.subunit.\"DFNNTPOMS_X_X_3.003.000.00.0.ear\".\"Bootstrapper.jar\".component.BootstrapCoreBean.START" => "java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
    Caused by: javax.ejb.EJBException: WFLYEJB0442: Unexpected Error
    Caused by: java.lang.ExceptionInInitializerError
    Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: jdk.internal.ref.Cleaner from [Module \"deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear\" from Service Module Loader]
    Caused by: java.lang.ClassNotFoundException: jdk.internal.ref.Cleaner from [Module \"deployment.DFNNTPOMS_X_X_3.003.000.00.0.ear\" from Service Module Loader]"}}
2022-01-25 07:06:59,068 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 40) WFLYSRV0010: Deployed "DFNNTPOMS_X_X_3.003.000.00.0.ear" (runtime-name : "DFNNTPOMS_X_X_3.003.000.00.0.ear")
2022-01-25 07:06:59,076 INFO  [org.jboss.as.controller] (Controller Boot Thread) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.deployment.subunit."DFNNTPOMS_X_X_3.003.000.00.0.ear"."Bootstrapper.jar".component.BootstrapCoreBean.START: java.lang.IllegalStateException: WFLYEE0042: Failed to construct component instance
`

**Comment by JerryShea** [comment]
I have ran the Chronicle Map unit tests under Oracle Java 11 and all good
```
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: /opt/apache-maven-3.8.2
Java version: 11.0.11, vendor: Oracle Corporation, runtime: /usr/lib/jvm/jdk-11.0.11
```
Maybe something else in your environment?

**Comment by isharawijesinghe** [comment]
Can you look into the exception I have posted? it says `jdk.internal.ref.Cleaner` class can not be found

**Comment by isharawijesinghe** [comment]
According to Oracle documentaion https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/ref/Cleaner.html it has
`java.lang.ref.Cleaner`

**Comment by isharawijesinghe** [comment]
![image](https://user-images.githubusercontent.com/26687701/150905587-f397f771-0ae6-4cb4-b260-8719a13b9484.png)

`net.openhft.chronicle.hash.impl.util.CleanerUtils` class required "jdk.internal.ref.Cleaner" which can not be found ?
