### ISSUE TITLE
NPE in DataAccess.copy

### ISSUE THREAD

**Issue by maxim5** [OpenHFT/Chronicle-Map#399]
```
java.lang.NullPointerException: Cannot invoke "net.openhft.chronicle.hash.serialization.DataAccess.copy()" because "net.openhft.chronicle.map.impl.CompiledMapQueryContext.m().valueDataAccess" is null
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.<init>(CompiledMapQueryContext.java:418) ~[chronicle-map-3.21.86.jar:3.21.86]
	at net.openhft.chronicle.map.VanillaChronicleMap.newQueryContext(VanillaChronicleMap.java:479) ~[chronicle-map-3.21.86.jar:3.21.86]
	at net.openhft.chronicle.map.VanillaChronicleMap.q(VanillaChronicleMap.java:455) ~[chronicle-map-3.21.86.jar:3.21.86]
	at net.openhft.chronicle.map.VanillaChronicleMap.mapContext(VanillaChronicleMap.java:486) ~[chronicle-map-3.21.86.jar:3.21.86]
	at net.openhft.chronicle.map.VanillaChronicleMap.queryContext(VanillaChronicleMap.java:540) ~[chronicle-map-3.21.86.jar:3.21.86]
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:896) ~[chronicle-map-3.21.86.jar:3.21.86]
```

**Comment by minborg** [comment]
We made some updates to Map a while ago. Would it be possible for you to try a later 3.22 version such as chronicle-map-3.22ea6

**Comment by JerryShea** [comment]
Closing as no response received
