### ISSUE TITLE
posix_fallocate() returned 28

### ISSUE THREAD

**Issue by shivamka1** [OpenHFT/Chronicle-Map#405]
Trying to creat chronicle maps file:
```java
ChronicleMap.of(LongValue.class, LongValue.class)
                .name("ids")
                .entries(1024 * 1024 * 1024)
                .createPersistedTo(new File("/tmp", "ids.dat"));
```

pom.xml
```xml
<dependency>
    <groupId>net.openhft</groupId>
    <artifactId>chronicle-map</artifactId>
    <version>3.21.86</version>
</dependency>
```

Throws exception:
```
[error] Exception in thread "main" java.io.IOException: posix_fallocate() returned 28
[error] 	at net.openhft.chronicle.hash.impl.util.jna.PosixFallocate.fallocate(PosixFallocate.java:25)
[error] 	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.fallocate(VanillaChronicleHash.java:1073)
[error] 	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.map(VanillaChronicleHash.java:1058)
[error] 	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createMappedStoreAndSegments(VanillaChronicleHash.java:511)
[error] 	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithNewFile(ChronicleMapBuilder.java:1850)
[error] 	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1748)
[error] 	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1593)
```

What can I do to fix this?

**Comment by minborg** [comment]
During the past months, we have updated Map and fixed numerous issues. Are you able to update to the latest version chronicle-map-3.22ea6?

**Comment by shivamka1** [comment]
This issue was caused because `.entries(1024 * 1024 * 1024)` was creating a file of size `35G` but my `/tmp` disk space was smaller. I changed the location to create `ids.dat` to a disk with larger space and it worked! Thanks.
