### ISSUE TITLE
Reading map  using ChronicleMap-3 ( created from Chroncile-map2 library)

### ISSUE THREAD

**Issue by priyamvar** [OpenHFT/Chronicle-Map#436]
We were using Chroncile Map2. and want to upgrade to ChronilceMap3 .
In some scenarios, we might want to read persisted map (created using ChornicleMap2) using ChronicleMap3
 
Error while reading persisted File:
Exception in thread "main" java.io.IOException: file=I:\test\map The file is shorter than the header size: 775684352, file size: 9227776
                at net.openhft.chronicle.hash.impl.VanillaChronicleHash.throwRecoveryOrReturnIOException(VanillaChronicleHash.java:229)
                at net.openhft.chronicle.map.ChronicleMapBuilder.readSelfBootstrappingHeader(ChronicleMapBuilder.java:427)
                at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1850)
                at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1715)
                at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1595)
                at chronicle.test.ReadCurrentBusinessDayMap.main(ReadCurrentBusinessDayMap.java:31)

**Comment by JerryShea** [comment]
Hi @priyamvar, for prioritised support of old versions can I point you to https://chronicle.software/support/

**Comment by priyamvar** [comment]
Hi Jerry,
Thanks for your timely response.
I am asking this question in general. if there is a possbility of reading chronicle map2 from chronicle map-3?
