### ISSUE TITLE
Cannot Resolve Class Error (Maven latest non-snapshot)

### ISSUE THREAD

**Issue by WilliamDunne** [OpenHFT/Chronicle-Map#44]
Pulling this error when starting up a map on one server that shares a file. Doesn't happen if the file doesn't already exist:

Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: net.openhft.chronicle.hash.impl.VanillaChronicleHash

I'm working to find a solution, but not sure if I will have any luck.

Full trace:

Exception in thread "main" java.lang.AssertionError: java.lang.reflect.InvocationTargetException
	at net.openhft.chronicle.map.ChronicleMapBuilder.deserializeHeaderViaXStream(ChronicleMapBuilder.java:1345)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1260)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1231)
	at co.mimex.UserFunctions.init(UserFunctions.java:317)
	at co.mimex.Main.main(Main.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.openhft.chronicle.map.ChronicleMapBuilder.deserializeHeaderViaXStream(ChronicleMapBuilder.java:1342)
	... 9 more
Caused by: com.thoughtworks.xstream.converters.ConversionException: net.openhft.chronicle.hash.impl.VanillaChronicleHash : net.openhft.chronicle.hash.impl.VanillaChronicleHash
---- Debugging information ----
message             : net.openhft.chronicle.hash.impl.VanillaChronicleHash
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : net.openhft.chronicle.hash.impl.VanillaChronicleHash
class               : net.openhft.chronicle.map.ReplicatedChronicleMap
required-type       : net.openhft.chronicle.map.ReplicatedChronicleMap
converter-type      : com.thoughtworks.xstream.converters.reflection.SerializableConverter
path                : /net.openhft.chronicle.map.ReplicatedChronicleMap/net.openhft.chronicle.hash.impl.VanillaChronicleHash
line number         : 2
version             : 2.3.2
-------------------------------
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:79)
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:65)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:66)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:50)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:134)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1185)
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1169)
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1049)
	... 14 more
Caused by: com.thoughtworks.xstream.mapper.CannotResolveClassException: net.openhft.chronicle.hash.impl.VanillaChronicleHash
	at com.thoughtworks.xstream.mapper.DefaultMapper.realClass(DefaultMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.DynamicProxyMapper.realClass(DynamicProxyMapper.java:55)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.PackageAliasingMapper.realClass(PackageAliasingMapper.java:88)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ClassAliasingMapper.realClass(ClassAliasingMapper.java:79)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.ArrayMapper.realClass(ArrayMapper.java:74)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.SecurityMapper.realClass(SecurityMapper.java:71)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.MapperWrapper.realClass(MapperWrapper.java:30)
	at com.thoughtworks.xstream.mapper.CachingMapper.realClass(CachingMapper.java:47)
	at com.thoughtworks.xstream.converters.reflection.SerializableConverter.doUnmarshal(SerializableConverter.java:447)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.unmarshal(AbstractReflectionConverter.java:257)
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:72)

**Comment by MrDunne** [comment]
Ok, this module actually hadn't updated the version from Maven. Updated and now pulling this issue:

Exception in thread "main" java.lang.NoSuchMethodError: net.openhft.lang.io.serialization.BytesMarshallableSerializer.create()Lnet/openhft/lang/io/serialization/ObjectSerializer;

**Comment by MrDunne** [comment]
ChronicleMapBuilder<String, Integer> builderr =
            ChronicleMapBuilder.of(String.class, Integer.class).replication((byte) 2, tcpConfigServer4);
MOst builders work, breaks here.

**Comment by MrDunne** [comment]
Updating lang fixed that. New issue:

net.openhft.lang.io.AbstractBytes.writeUTF0

**Comment by leventov** [comment]
@MrDunne what does combination of `chronicle-map:2.3.4` and `lang:6.7.3` give?

**Comment by MrDunne** [comment]
Caused by: com.thoughtworks.xstream.converters.ConversionException: net.openhft.chronicle.hash.impl.VanillaChronicleHash : net.openhft.chronicle.hash.impl.VanillaChronicleHash
---- Debugging information ----
message             : net.openhft.chronicle.hash.impl.VanillaChronicleHash
cause-exception     : com.thoughtworks.xstream.mapper.CannotResolveClassException
cause-message       : net.openhft.chronicle.hash.impl.VanillaChronicleHash
class               : net.openhft.chronicle.map.ReplicatedChronicleMap
required-type       : net.openhft.chronicle.map.ReplicatedChronicleMap
converter-type      : com.thoughtworks.xstream.converters.reflection.SerializableConverter
path                : /net.openhft.chronicle.map.ReplicatedChronicleMap/net.openhft.chronicle.hash.impl.VanillaChronicleHash
line number         : 2
version             : 2.3.4
-------------------------------


I'm guessing that this is because in the other applications I use 3.** because I needed access to MapEntryOperations

**Comment by leventov** [comment]
@MrDunne that's for sure. Chronicle Map 2 and 3 are not compatible. Unfortunately Chronicle Map 3 is still missing some functionality of Chronicle Map 2, e. g. ability to access the Map remotely (stateless clients). When this and a couple of other issues are fixed Chronicle Map 3 beta, and then production release will be published. This should happen in the course of about a month.

**Comment by MrDunne** [comment]
Hmm, I'm not using anything like that though. Its replicated over TCP but I'm accessing it locally..

**Comment by leventov** [comment]
@MrDunne in this case, why you need Chronicle Map 2?

**Comment by MrDunne** [comment]
I don't, I need Chronicle Map 3 to use the MapEntryOperations. I was using the latest 3.* on all of the things and I was getting that error.
