### ISSUE TITLE
Tuning ChronicleMap in concurrent environment

### ISSUE THREAD

**Issue by keynmol** [OpenHFT/Chronicle-Map#48]
Hi.

We're using ChronicleMap with Spark, for a fixed map that we create like this:

```
 val cmap = ChronicleMapBuilder.of(classOf[String], classOf[String]).entries(entries)
      .averageKeySize(averageKeySize)
      .averageValueSize(averageValueSize)
      .actualSegments(500)
      .createPersistedTo(outputFile)
```

Where `averageKeySize = averageValueSize = 83` and there's seven million entries.

We pre-created this map and in production we only read from it (using standard `get`). So when I was varying number of spark workers (using `--master local[N]`), I noticed that the performance drops horribly when going from 12 to 15 workers). 12 workers - everything works, 15 - incredibly slow. Our standard environment has 48 workers, and there Spark was reading input at about 20 megabytes a minute compared to 350 megabytes in 5 seconds without using the ChronicleMap.

When using the same code but not using the map, any number of workers works just fine.

I understand it could have something to do with lock acquisition, but on WARN level I haven't seen any messages. 

Could you suggest what we're doing wrong?

**Comment by leventov** [comment]
Some suggestions:

 - Ensure you are using the latest version (3.1.4-alpha)
 - Verify the created Map has the configured number of segments, using [`map.segments()`](http://static.javadoc.io/net.openhft/chronicle-map/3.1.4-alpha/net/openhft/chronicle/hash/ChronicleHash.html#segments--) method. (Of cause, if you configured this number, it *must* be returned, otherwise it is a bug)
 
If it doesn't help. and `map.segments()` shows the right number, it requires further investigation.

Not directly related, but important notes about Chronicle Map usage:

 - Don't forget to configure number of entries stored! Using `builder.entries(N)` call. If it varies, configure the number, so that the actual number of entries is less or equal to the configured in 99.9% of cases, and also configure `builder.maxBloatFactor(f)`, where `f` is *theoretical maximum* of stored entries, divided by the configured `entries`.
  - On the other hand, it might silently lead to bad performance, if for some reasons (bad keys distribution, wrong (lower than actual) `entries` number configured, bugs) Chronicle Map creates too much *tiers*. If you statically fill Chronicle Map, and then use it for long time, you could configure `builder.allowSegmentTiering(false)`, and try to choose as low `builder.entries(N)` as it doesn't throw `IllegalStateException: segment overflow` during the filling phase.
 - If configuring number of segments, prefer power-of-2 numbers, i. e. 512
 - Prefer `minSegments(512)` to `actualSegments(512)`.
 - Configuring `averageKeySize()` and `averageValueSize()` is error-prone -- off-by-ones, accounting/not the space used to store the size of serialized chunk itself. Prefer `averageKey(K)`/`averageValue(V)`
  - On the other hand, it might silently lead to bad performance, if Chronicle Map fails to pick up optimized serializer, or you forget to configure custom serializer, and it falls back to JDK serialization, which include serialized class into each serialized key/value bytes chunk. It shouldn't be an issue with `java.lang.String` keys/values, because JDK special-case them in turn and serialize optimally, but could be so, e. g. for `java.util.Set`  or `java.util.List` values

**Comment by keynmol** [comment]
Thanks for those advices.

I tried to change the version to 3.1.4-alpha in `build.sbt`, and got this:
```
[warn] io problem while parsing ivy file: https://repo1.maven.org/maven2/net/openhft/chronicle-algorithms/1.1.0/chronicle-algorithms-1.1.0.pom: Impossible to import module for file:/Users/velvetbaldmime/.ivy2/cache/net.openhft/chronicle-algorithms/ivy-1.1.0.xml.original. Import=net.openhft#chronicle-bom;1.8.11-SNAPSHOT
[info] Resolving net.openhft#chronicle-bom;1.8.11-SNAPSHOT ...
[warn] io problem while parsing ivy file: https://oss.sonatype.org/content/repositories/public/net/openhft/chronicle-algorithms/1.1.0/chronicle-algorithms-1.1.0.pom: Impossible to import module for file:/Users/velvetbaldmime/.ivy2/cache/net.openhft/chronicle-algorithms/ivy-1.1.0.xml.original. Import=net.openhft#chronicle-bom;1.8.11-SNAPSHOT
[warn]  module not found: net.openhft#chronicle-algorithms;1.1.0
[warn] ==== local: tried
[warn]   /Users/velvetbaldmime/.ivy2/local/net.openhft/chronicle-bom/1.8.11-SNAPSHOT/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/net/openhft/chronicle-bom/1.8.11-SNAPSHOT/chronicle-bom-1.8.11-SNAPSHOT.pom
[warn] ==== sonatype-public: tried
[warn]   https://oss.sonatype.org/content/repositories/public/net/openhft/chronicle-bom/1.8.11-SNAPSHOT/chronicle-bom-1.8.11-SNAPSHOT.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: net.openhft#chronicle-algorithms;1.1.0: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]
[warn]  Note: Unresolved dependencies path:
[warn]      net.openhft:chronicle-algorithms:1.1.0
[warn]        +- net.openhft:chronicle-map:3.1.4-alpha (...../build.sbt#L24-25)
sbt.ResolveException: unresolved dependency: net.openhft#chronicle-algorithms;1.1.0: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:123)
    at sbt.IvySbt.withIvy(Ivy.scala:120)
    at sbt.IvySbt$Module.withModule(Ivy.scala:151)
    at sbt.IvyActions$.updateEither(IvyActions.scala:157)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error] (*:update) sbt.ResolveException: unresolved dependency: net.openhft#chronicle-algorithms;1.1.0: not found
``` 

Changing to 2.3.7 didn't throw any exception but I started seeing warning messages:

```
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
writersWaiting has underflowed
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Grabbing lock held by threadId: 0
15/10/09 15:56:50 WARN ChronicleHashErrorListeners$LoggingErrorListener: Failed to unlock as expected
java.lang.IllegalMonitorStateException: writersLock underflow 0
        at net.openhft.lang.io.AbstractBytes.unlockRWWriteLock(AbstractBytes.java:3049)
        at net.openhft.chronicle.map.VanillaChronicleMap$Segment.readUnlock(VanillaChronicleMap.java:1932)
        at net.openhft.chronicle.map.VanillaChronicleMap$Segment.acquire(VanillaChronicleMap.java:2019)
        at net.openhft.chronicle.map.VanillaChronicleMap.lookupUsing(VanillaChronicleMap.java:667)
        at net.openhft.chronicle.map.VanillaChronicleMap.lookupUsing(VanillaChronicleMap.java:653)
        at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:619)
```

**Comment by RobAustin** [comment]
I think we ( may ) have a build issue and may have to re-release.

**Comment by keynmol** [comment]
So, operating under the assumption that I can't use 3.1.4-alpha yet, I can't use majority of the advices @leventov posted (seems like those functions just don't exist in 2.3.7).

The map we use is pre-built, number of entries is exact and doesn't change. Here's the code that creates the file (Scala):

```scala
def fillStore(rawRedirects: File, outputFile: File) = {
    val redsEstimation = new DbpediaRedirectParser(rawRedirects.getAbsolutePath)
    println("Calculating stats for memory-mapped redirects store...")
    val estimatedSizes = redsEstimation.redirectMap
                          .map {case (u1, u2) => (SizeEstimator.estimate(u1), SizeEstimator.estimate(u2))}
                          .foldLeft((0L, 0L, 0L)) {(sums, el) => (sums._1 + el._1, sums._2 + el._2, sums._3 + 1)}

    val (entries, averageKeySize, averageValueSize) = (estimatedSizes._3, estimatedSizes._1/estimatedSizes._3, estimatedSizes._2/estimatedSizes._3)


    val cmap = ChronicleMapBuilder.of(classOf[String], classOf[String]).entries(entries)
      .averageKeySize(averageKeySize)
      .averageValueSize(averageValueSize)
      .minSegments(512)
      .createPersistedTo(outputFile)

    val redirects = new DbpediaRedirectParser(rawRedirects.getAbsolutePath)

    println("Inserting redirects...")
    val start = System.currentTimeMillis()
    redirects.redirectMap.foreach { case(u1, u2) => cmap.put(u1.toLowerCase, u2)}
    val duration = System.currentTimeMillis() - start

    println("Sick! all done in " + (duration.toDouble/1000).toString + " seconds ")

  }
```

And we use the map through StackObjectPool:

```scala
class ChronicleMapFactory(mapLocation: File) extends PoolableObjectFactory[ChronicleMap[String, String]] {
  type RedirectMap = ChronicleMap[String, String]
  // when we make an object it's already connected
  def makeObject = {
    val m = mapBuilder().createPersistedTo(mapLocation)
    // println("Num segments: " + m.segments())
    m
  }

  def mapBuilder() = ChronicleMapBuilder.of(classOf[String], classOf[String])

  // quit & disconnect
  def destroyObject(rc: RedirectMap): Unit = {
   rc.close()
  }

  // noop: we want to have it connected
  def passivateObject(rc: RedirectMap): Unit = {}
  def validateObject(rc: RedirectMap) = true

  // noop: it should be connected already
  def activateObject(rc: RedirectMap): Unit = {}
}


class ChronicleMapPool(mapLocation: File) {
  val pool = new StackObjectPool(new ChronicleMapFactory(mapLocation))
  override def toString = "ChronicleMapPool(" + mapLocation.getAbsolutePath + ")"

  def withMap[T](body: ChronicleMap[String, String] => T) = {
    val client = pool.borrowObject
    try {
      body(client)
    } finally {
      pool.returnObject(client)
    }
  }

  // close pool & free resources
  def close = pool.close
}

object ChronicleMapRedirectStore extends RedirectStore {
  var mapLocation: File = null
  lazy val clients = new ChronicleMapPool(mapLocation)

  def resolve(wikipediaId: String): String = {
    clients.withMap {
      client => {
        val redirect = client.get(wikipediaId.toLowerCase)

        redirect match {
          case null => wikipediaId
          case _ => redirect
        }
      }
    }
  }
}
```

Those lock messages - I suspect they're related to https://github.com/OpenHFT/Chronicle-Map/issues/20 - and probably in Spark environment that lock could be held for some time unnecessarily.

**Comment by leventov** [comment]
- For String keys/values, you should compute the length for `averageKeySize/averageValueSize` using UTF-8 encoding, e. g. `AbstractBytes.findUTFLength()`

 - You shouldn't pool `ChronicleMap` objects within a JVM, in opposite, the recommendation is to have exactly one `ChronicleMap` instance per actual map (identified by the file) per JVM. Having several on-heap instances -- should work, but probably worse.

**Comment by keynmol** [comment]
Not sure which one of those did it, but it seems like it started scaling better!

```
w/ ChronicleMap, 5 workers = 8m
w/o ChronicleMap, 5 workers = 6m
w/o ChronicleMap, 10 workers = 4m
w/o ChronicleMap, 15 workers = 4m
w/ ChronicleMap, 10 workers = 15m+ (had to stop at about 10% done)
w/ ChronicleMap + findUTFLength + 1 instance per JVM, 10 workers = 5m26.784s
w/ ChronicleMap + findUTFLength + 1 instance per JVM, 15 workers = ~5m
```

If you guys don't mind, I'll keep this issue open while I test other jobs with the new fix. Also, do you have an idea when 3.1.4-alpha will be re-released?

**Comment by leventov** [comment]
Ok, let it stay open.

More likely the next release will be beta

**Comment by keynmol** [comment]
Okay, looks like it's all good. 

Thanks.
