### ISSUE TITLE
IllegalArgumentException on byte[]

### ISSUE THREAD

**Issue by nguyenvanthan** [OpenHFT/Chronicle-Map#55]
Hi,

I use version 2.3.9.

According to the documentation, it should be possible to store byte array but when i initialize the chronicle map, i have some IllegalArgumentException : 
``` 
java.lang.IllegalArgumentException: type must be an interface, was class [B
	at net.openhft.lang.model.DataValueModelImpl.<init>(DataValueModelImpl.java:62)
	at net.openhft.lang.model.DataValueModelImpl.<init>(DataValueModelImpl.java:227)
	at net.openhft.lang.model.DataValueModelImpl.<init>(DataValueModelImpl.java:227)
	at net.openhft.lang.model.DataValueModels.acquireModel(DataValueModels.java:46)
	at net.openhft.lang.model.DataValueGenerator.acquireNativeClass(DataValueGenerator.java:809)
	at net.openhft.lang.model.DataValueClassCache.directClassFor(DataValueClassCache.java:48)
	at net.openhft.lang.model.DataValueClasses.directClassFor(DataValueClasses.java:55)
	at net.openhft.chronicle.map.SerializationBuilder.configureByDefault(SerializationBuilder.java:118)
	at net.openhft.chronicle.map.SerializationBuilder.<init>(SerializationBuilder.java:95)
	at net.openhft.chronicle.map.ChronicleMapBuilder.<init>(ChronicleMapBuilder.java:156)
	at net.openhft.chronicle.map.ChronicleMapBuilder.of(ChronicleMapBuilder.java:182)
``` 

Here is my value Interface :
```
public interface IValueCache {

    // it's just an enum
    LoadingState getState();

    void setState(@NotNull LoadingState state);

    byte[] getBinaryData();

    void setBinaryData(@NotNull byte[] data);

}
```

Do you have any idea ?

Thanks

**Comment by RobAustin** [comment]
What is type loadingState, try it without this.

**Comment by leventov** [comment]
It is possible to have the key or the value type of `byte[]` for the Chronicle Map itself, i. e.
```java
ChronicleMap<IntValue, byte[]> map = ChronicleMapBuilder.of(IntValue.class, byte[].class)...
```

You have `byte[]` field *inside* the data value generated interface, that is not supported automatically.

You should provide the custom marshaller via `ChronicleMapBuilder.valueMarshaller()` or `valueMarshallers()` -- see Javadocs for these methods for more info
