### ISSUE TITLE
chronicle map error on Externalizable

### ISSUE THREAD

**Issue by JohnLCaron** [OpenHFT/Chronicle-Map#61]
in upgrading from 2.1.7 to 2.3.9, using Externalizable as the type no longer works. The concrete class does work. perhaps this was deliberate, but cant find any release notes anywhere...

here is a test recreating the problem.

```java
import net.openhft.chronicle.map.ChronicleMap;
import net.openhft.chronicle.map.ChronicleMapBuilder;

import java.io.*;

public class DatasetTrackerTest implements Externalizable {

  public static void main(String[] args) throws IOException {

    // replace Externalizable with DatasetTrackerTest to make this work
    ChronicleMapBuilder<String, Externalizable> builder = ChronicleMapBuilder.of(String.class, Externalizable.class)
            .averageValueSize(200).entries(100);

    File dbFile = new File("C:/Temp/cdb.tmp");

    ChronicleMap<String, Externalizable> datasetMap = builder.createPersistedTo(dbFile);
    System.out.printf("%s%n", datasetMap);

    String key = "esg_dataroot/obs4MIPs/observations/atmos/husNobs/mon/grid/NASA-JPL/AIRS/v20110608/husNobs_AIRS_L3_RetStd-v5_200209-201105.nc";
    datasetMap.put(key, new DatasetTrackerTest("value"));

    DatasetTrackerTest saved = (DatasetTrackerTest) datasetMap.get(key);
    assert saved.value.equals("value");
    System.out.printf("%s%n", saved.value);

    datasetMap.close();
  }


  String value;

  public DatasetTrackerTest(String value) {
    this.value = value;
  }

  @Override
  public void writeExternal(ObjectOutput out) throws IOException {
    out.writeUTF(value);
  }

  @Override
  public void readExternal(ObjectInput in) throws IOException, ClassNotFoundException {
    value = in.readUTF();
  }
}
```

**Comment by JohnLCaron** [comment]
stack trace:

```
Exception in thread "main" java.lang.IllegalStateException: Unknown type 
	at net.openhft.lang.io.serialization.BytesMarshallableSerializer.readSerializable(BytesMarshallableSerializer.java:160)
	at net.openhft.chronicle.map.SerializationBuilder$SerializableMarshaller.read(SerializationBuilder.java:485)
	at net.openhft.chronicle.hash.serialization.internal.BytesReaders$SimpleBytesReader.read(BytesReaders.java:70)
	at net.openhft.chronicle.map.VanillaChronicleMap.readValue(VanillaChronicleMap.java:1165)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.readValueAndNotifyGet(VanillaChronicleMap.java:2124)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.acquireWithoutLock(VanillaChronicleMap.java:2046)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.acquire(VanillaChronicleMap.java:2018)
	at net.openhft.chronicle.map.VanillaChronicleMap.lookupUsing(VanillaChronicleMap.java:671)
	at net.openhft.chronicle.map.VanillaChronicleMap.lookupUsing(VanillaChronicleMap.java:657)
	at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:623)
	at thredds.server.catalog.tracker.DatasetTrackerTest.main(DatasetTrackerTest.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```

**Comment by leventov** [comment]
@JohnLCaron see the test I've added: https://github.com/OpenHFT/Chronicle-Map/commit/5cca6cb3a4d695103fa9f53f6e4fd05e8733b539 it passes with `3.2.0-beta` version, so you could try to switch to the new version. If you wish to stay on 2.x branch, you could workaround the issue by implementing custom marshaller classes, see `ChronicleMapBuilder#valueMarshallers()` and similar methods.

**Comment by JohnLCaron** [comment]
Hi @leventov thanks i have a workaround by using concrete class instead of Externalizable. thanks for quick response.

**Comment by leventov** [comment]
If you actually have a concrete key or value type, you should use it instead of `Object`, `Externalizable`, etc., that's for sure. It permits Chronicle Map to serialize/deserialize more effciently, because it doesn't waste space to write the class along with each value.

**Comment by JohnLCaron** [comment]
makes sense, thanks.
