### ISSUE TITLE
Chronicle-Map 3.x cannot load in JRE

### ISSUE THREAD

**Issue by davejoyce** [OpenHFT/Chronicle-Map#72]
In Chronicle-Map 3.x, it appears that `ChronicleMapBuilder` requires the presence of JavacTool or some other implementation of `javax.tools.JavaCompiler`. When I attempt to deploy and start up in a JRE, I get this exception:

```
java.lang.NoClassDefFoundError: com/sun/tools/javac/api/JavacTool
        at net.openhft.compiler.CompilerUtils.reset(CompilerUtils.java:75) ~[compiler-2.2.1.jar:na]
        at net.openhft.compiler.CompilerUtils.<clinit>(CompilerUtils.java:64) ~[compiler-2.2.1.jar:na]
        at net.openhft.chronicle.values.ValueModel.createClass(ValueModel.java:311) ~[chronicle-values-1.0.2-alpha.jar:na]
        at net.openhft.chronicle.values.ValueModel.createNativeClass(ValueModel.java:286) ~[chronicle-values-1.0.2-alpha.jar:na]
        at net.openhft.chronicle.values.ValueModel.nativeClass(ValueModel.java:268) ~[chronicle-values-1.0.2-alpha.jar:na]
        at net.openhft.chronicle.values.Values.nativeClassFor(Values.java:51) ~[chronicle-values-1.0.2-alpha.jar:na]
        at net.openhft.chronicle.values.Values.newNativeReference(Values.java:38) ~[chronicle-values-1.0.2-alpha.jar:na]
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.createGlobalMutableState(VanillaChronicleHash.java:328) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.initOwnTransients(VanillaChronicleHash.java:377) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at net.openhft.chronicle.hash.impl.VanillaChronicleHash.initTransients(VanillaChronicleHash.java:373) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at net.openhft.chronicle.map.VanillaChronicleMap.initTransients(VanillaChronicleMap.java:149) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at net.openhft.chronicle.map.VanillaChronicleMap.<init>(VanillaChronicleMap.java:105) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at net.openhft.chronicle.map.ChronicleMapBuilder.newMap(ChronicleMapBuilder.java:1563) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1482) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1374) ~[chronicle-map-3.4.1-beta.jar:3.4.1-beta]
        at com.wfs.rushmore.storage.support.ChronicleMapBuilderBean.createInstance(ChronicleMapBuilderBean.java:293) ~[stateservice-1.3.jar:na]
        at com.wfs.rushmore.storage.support.ChronicleMapBuilderBean.createInstance(ChronicleMapBuilderBean.java:50) ~[stateservice-1.3.jar:na]
        at org.springframework.beans.factory.config.AbstractFactoryBean.afterPropertiesSet(AbstractFactoryBean.java:134) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at com.wfs.rushmore.storage.support.ChronicleMapBuilderBean.afterPropertiesSet(ChronicleMapBuilderBean.java:193) ~[stateservice-1.3.jar:na]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        ... 18 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
```

Is there a way to invoke a create method on ChronicleMapBuilder in a JRE environment?

**Comment by davejoyce** [comment]
Resolved this by using the [Server JRE package](http://www.oracle.com/technetwork/java/javase/downloads/server-jre8-downloads-2133154.html).

**Comment by alex3305** [comment]
Could this be reopened since using the Server JRE is only a workaround and not a permanent solution.

**Comment by leventov** [comment]
You need to have `tools.jar` in classpath to perform runtime compilation that is used by Chronicle Values hence Chronicle Map. @alex3305 why you need to run Chronicle Map with client JRE?

**Comment by alex3305** [comment]
For an embedded, persistable key value store. Preferably with multi-threading support. It seems that Chronicle Map is currently one of the only stable and well documented libraries to provide this. I use this in an application I'm currently developing and I intent to use the JRE to run it.

**Comment by leventov** [comment]
@alex3305 have you seen PalDB?

**Comment by leventov** [comment]
@alex3305  also https://github.com/JetBrains/xodus
