### ISSUE TITLE
Exception while reading from the existing file -ChronicleMap v3.8.0

### ISSUE THREAD

**Issue by chauhraj** [OpenHFT/Chronicle-Map#85]
I am trying to use ChronicleMap to share data between different JVM processes. I am able to write the data successfully but I am getting the following error. My application is a scala application and I don't see if the scala can make a difference. I am setting avaerageKeySize, maxBloatFactor, averageValueSize, entries prior to create a Map instance.It uses chronicle-core-1.6.2 jars.

`Exception in thread "main" java.lang.AssertionError: java.lang.IllegalArgumentException: No enum constant net.openhft.chronicle.hash.serialization.impl.StopBitSizeMarshaller.{}
	at net.openhft.chronicle.core.util.ObjectUtils.convertTo0(ObjectUtils.java:142)
	at net.openhft.chronicle.core.util.ObjectUtils.convertTo(ObjectUtils.java:130)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:440)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.objectWithInferredType(TextWire.java:2482)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.typedMarshallable(TextWire.java:2290)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.readMarshallableFields(VanillaChronicleHash.java:240)
	at net.openhft.chronicle.map.VanillaChronicleMap.readMarshallableFields(VanillaChronicleMap.java:107)
	at net.openhft.chronicle.hash.impl.VanillaChronicleHash.readMarshallable(VanillaChronicleHash.java:225)
	at net.openhft.chronicle.wire.SerializationStrategies$1.readUsing(SerializationStrategies.java:22)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.marshallable(TextWire.java:2228)
	at net.openhft.chronicle.wire.ValueIn.object(ValueIn.java:429)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.objectWithInferredType(TextWire.java:2482)
	at net.openhft.chronicle.wire.TextWire$TextValueIn.typedMarshallable(TextWire.java:2290)
	at net.openhft.chronicle.map.ChronicleMapBuilder.openWithExistingFile(ChronicleMapBuilder.java:1598)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1444)
	at net.openhft.chronicle.map.ChronicleMapBuilder.recoverPersistedTo(ChronicleMapBuilder.java:1416)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createOrRecoverPersistedTo(ChronicleMapBuilder.java:1410)`

**Comment by leventov** [comment]
You should use chronicle-core-1.3.6.jar and chronicle-wire-1.3. 6.jar. It is a known thing that using Chronicle Map 3.8.0 with newer Wire versions leads to errors like yours.
