### ISSUE TITLE
java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool

### ISSUE THREAD

**Issue by mikomarrache** [OpenHFT/Chronicle-Map#91]
Hi,

I get the following error when running my app using a JRE:

Exception in thread "Thread-1" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
        at net.openhft.chronicle.values.CompilerUtils.reset(CompilerUtils.java:61)
        at net.openhft.chronicle.values.CompilerUtils.<clinit>(CompilerUtils.java:50)
        at net.openhft.chronicle.values.ValueModel.createClass(ValueModel.java:347)
        at net.openhft.chronicle.values.ValueModel.createNativeClass(ValueModel.java:322)
        at net.openhft.chronicle.values.ValueModel.nativeClass(ValueModel.java:298)
        at net.openhft.chronicle.values.Values.nativeClassFor(Values.java:82)
        at net.openhft.chronicle.hash.serialization.impl.ValueReader.initTransients(ValueReader.java:64)
        at net.openhft.chronicle.hash.serialization.impl.ValueReader.<init>(ValueReader.java:47)
        at net.openhft.chronicle.hash.serialization.impl.SerializationBuilder.configureByDefault(SerializationBuilder.java:81)
        at net.openhft.chronicle.hash.serialization.impl.SerializationBuilder.<init>(SerializationBuilder.java:64)
        at net.openhft.chronicle.map.ChronicleMapBuilder.<init>(ChronicleMapBuilder.java:191)
        at net.openhft.chronicle.map.ChronicleMapBuilder.of(ChronicleMapBuilder.java:256)
        at net.openhft.chronicle.map.ChronicleMap.of(ChronicleMap.java:68)
        at ------------------------------------------------------------------------
Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at net.openhft.chronicle.values.CompilerUtils.reset(CompilerUtils.java:57)
        ... 13 more

No error when using a JDK - I guess tools.jar is needed? Maybe the dependency should be added to the Chronicle Map POM?

Thanks,
Mickael

**Comment by leventov** [comment]
Yes, you are right, JDK is needed because of tools.jar. A dep to the `tools.jar` used to be in the POM (with "system" scope), but was removed for some reason (will see, why).

BTW tools.jar might be made not required in some future versions of Chronicle Map, this is not an absolutely inherent dependency.

**Comment by peter-lawrey** [comment]
Hello Mickael,
As the tool uses the Compiler API you have to have the compiler it needs
installed. This compiler is not available on maven central so it must be
provided/installed separately.

Regards, Peter.

**Comment by peter-lawrey** [comment]
What we could do is give a more descriptive error message.

**Comment by felixunivers** [comment]
Good day,

my project runs fine under Netbeans IDE.
My POM.XML includes Chronicle map using:

`              <artifactId>maven-assembly-plugin</artifactId>
              <configuration>
                <descriptorRefs>
                  <descriptorRef>jar-with-dependencies</descriptorRef>
                </descriptorRefs>
.... etc. ... +
        <dependency>
          <groupId>net.openhft</groupId>
          <artifactId>chronicle-map</artifactId>
          <version>3.10.2-SNAPSHOT</version>
        </dependency>
`
Compiles fine
However the same issue of error at the command level execution as mentioned above.
Here is the error:

`Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
        at net.openhft.chronicle.values.CompilerUtils.reset(CompilerUtils.java:61)
        at net.openhft.chronicle.values.CompilerUtils.<clinit>(CompilerUtils.java:50) 
etc ....
`
Would you please provide a concrete solution (example of POM entries to filter out or add components; or other steps necessary) to be able to run a project using ChronicleMap from command line:

` java -jar myapp.jar`

Thank you.

**Comment by peter-lawrey** [comment]
Which version of the JDK are you using? This doesn't work with the JRE
alone.

**Comment by felixunivers** [comment]
Hello, after several months I am back to the ChronicleMap project, and was not able to resolve this issue with JavacTool.

When trying to execute myApp based on ChronicleMap API:

    java -jar myApp-00.00.01-SNAPSHOT-jar-with-dependencies.jar

getting the exception:

    Exception in thread "main" java.lang.AssertionError: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
    at net.openhft.chronicle.values.CompilerUtils.reset(CompilerUtils.java:62)

    Caused by: java.lang.ClassNotFoundException: com.sun.tools.javac.api.JavacTool
    at java.net.URLClassLoader.findClass(Unknown Source)

Here is my config:

OS Installed: Windows 10
Java Installed: JDK 1.8.0_131
Java Path: C:\Program Files\Java\jre1.8.0_131\bin\javaw.exe

ChronicleMaps tested: 3.10 - 3.13 - same problem for all these versions

Thank you.

**Comment by peter-lawrey** [comment]
Having the JDK installed somewhere isn't enough, you have to run the Javaw
from the JDK.

**Comment by felixunivers** [comment]
Got it working. Here is how in case someone else struggles with Windows and java configuration.

If you want to run your jar application (with the ChronicleMap API) the standard java way - e.g:

    java -jar myApp.jar

you must make sure your executing "java" is the JDK java and not JRE java.

This means you and your app. users will need to have JDK installed on your system 
and configured so that the JDK java is used, not the JRE java.

That's been clear to me from beginning, and I thought my system was running
JDK java, but it did not. Here is how I solved it.

In Windows (after you have installed JDK) you may have several locations/folders
specified in your system environment variables as the PATH to java.exe.

In my case I had 3 references to java. You can check that from command line:

    where java

My result was:

    C:\Program Files\Java\jre1.8.0_131\bin
    C:\Program Files\Java\jdk1.8.0_131\bin
    C:\ProgramData\Oracle\Java\javapath

As advised by others I added:
    JAVA_PATH variable and pointed it to:
        C:\Program Files\Java\jdk1.8.0_131

But that did not solve the issue and I was still running JRE, not JDK java.

I also checked the java control panel ("Configure Java" in start menu item).
First of all note that you must run it as administrator or no changes will stick -
that's what Oracle says. But for me after a reboot the settings were all back to
defaults and all my changes gone.

In case it works for you here are the steps:

- Windows start menu
- right-click "Configure Java"
- More > Run as administrator
- enter your admin. password 
  (if you do not see the password window, look for the icon on your task bar)
- Java Control panel will appear
- select tab: Java
- click: View
- select tab: System
- click: Find and navigate to your java JDK folder - e.g:
  C:\Program Files\Java\jdk1.8.0_131\bin
- click: Next
- you'll see: C:\Program Files\Java\jdk1.8.0_131\bin\javaw.exe
- click: Finish
- enable the added entry check-box and disable all others
- OK, OK

Now, this was supposed to specify my preference of JDK java over JRE java.
But is did not.

So, at the end I removed all references to java in my PATH - Windows system environment variables 
except the one for JDK:
    C:\Program Files\Java\jdk1.8.0_131\bin

That did it.

**Comment by HTGAzureX1212** [comment]
This is still technically an issue for those who want to run a certain application using a jlink runtime, but not a JDK.
