### ISSUE TITLE
ClassNotFoundException when loading value interface from web application

### ISSUE THREAD

**Issue by barabaka** [OpenHFT/Chronicle-Map#92]
I have the following issue when creating a map from web application environment (running from jetty maven plugin in intellij idea or from standalone tomcat). Looks like classloader problem but I can't figure out what exactly the issue is. Looks similar to the one described here: http://stackoverflow.com/questions/35814537/chronicle-map-classnotfoundexception-with-gradle-aspectj but stack trace is different.

Map is created like this:
ChronicleMapBuilder<String, TestMetric> builder = ChronicleMapBuilder
                .of(String.class, TestMetric.class)
                .averageKeySize(50)
                .entries(1000000);

(1) net.test.TestMetric is a custom value interface
(2) I can access the class via Class.forName(), it's present in the project.
(3) It works ok when doing the same from standalone java app
(4) chronicle-map-2.4.15, lang-6.8.2 and compiler-2.2.5 are used, so basically latest versions for java 7 (we can't go directly to java 8 at the moment)

Caused by: java.lang.AssertionError: java.lang.ClassNotFoundException: net.test.TestMetric$$Native
    at net.openhft.lang.model.DataValueGenerator.acquireNativeClass(DataValueGenerator.java:825)
    at net.openhft.lang.model.DataValueClassCache.directClassFor(DataValueClassCache.java:48)
    at net.openhft.lang.model.DataValueClasses.directClassFor(DataValueClasses.java:55)
    at net.openhft.chronicle.hash.serialization.internal.DataValueBytesMarshallers.acquireReaderClass(DataValueBytesMarshallers.java:72)
    at net.openhft.chronicle.hash.serialization.internal.DataValueBytesMarshallers.acquireBytesReader(DataValueBytesMarshallers.java:50)
    at net.openhft.chronicle.map.SerializationBuilder.configureByDefault(SerializationBuilder.java:95)
    at net.openhft.chronicle.map.SerializationBuilder.<init>(SerializationBuilder.java:72)
    at net.openhft.chronicle.map.ChronicleMapBuilder.<init>(ChronicleMapBuilder.java:152)
    at net.openhft.chronicle.map.ChronicleMapBuilder.of(ChronicleMapBuilder.java:178)
    at net.test.SegmentDataServiceChronicle.init(SegmentDataServiceChronicle.java:55)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:349)
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:300)
    at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
    ... 84 more
Caused by: java.lang.ClassNotFoundException: net.test.TestMetric$$Native
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:450)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:403)
    at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:155)
    at net.openhft.compiler.CachedCompiler.loadFromJava(CachedCompiler.java:75)
    at net.openhft.lang.model.DataValueGenerator.acquireNativeClass(DataValueGenerator.java:823)

**Comment by barabaka** [comment]
There are also many errors like this, however the jar is there and I can load net.openhft.lang.Compare class with Class.forName():

/net/test/TestMetric$$Native.java:3: error: package net.openhft.lang does not exist
import static net.openhft.lang.Compare.*;
                              ^
/net/test/TestMetric$$Native.java:7: error: package net.openhft.lang.io does not exist
import net.openhft.lang.io.Bytes;
                          ^
/net/test/TestMetric$$Native.java:8: error: package net.openhft.lang.io.serialization does not exist
import net.openhft.lang.io.serialization.BytesMarshallable;
                                        ^
/net/test/TestMetric$$Native.java:9: error: package net.openhft.lang.model does not exist
import net.openhft.lang.model.Byteable;
                             ^
/net/test/TestMetric$$Native.java:10: error: package net.openhft.lang.model does not exist
import net.openhft.lang.model.Copyable;

**Comment by leventov** [comment]
Chronicle Values project is not designed to work with Java-Lang and Chronicle Map 2.x. It should be used with the "new" stack: Chronicle-Bytes, Chronicle Map 3.x.

**Comment by barabaka** [comment]
@leventov Correct me if I am wrong, but I am not using Chronicle Values project, I use custom interface the same way it's documented for version 2.x: https://github.com/OpenHFT/Chronicle-Map/tree/chronicle-map-2.4.15, and it works pretty well except the case with web application context. Am I doing to wrong? Should I only use classes for version 2.x?

**Comment by leventov** [comment]
Yes, there are issues with dynamic loading of generated Java source code. They are addressed for Chronicle Values, but untouched for old "data value generation" from Java-Lang. Java-Lang is not supported anymore for free. So you could either

 - resolve that issues yourself, by repeating existing research:
    - some recent commits to https://github.com/OpenHFT/Java-Runtime-Compiler and https://github.com/OpenHFT/Chronicle-Values
    - Also this discussion: https://github.com/OpenHFT/Java-Runtime-Compiler/issues/19 and http://stackoverflow.com/questions/38467876/how-to-get-the-javacompiler-to-use-a-provided-classloader-to-find-a-class could be useful resources
 - or switch to Chronicle Map 3.x

**Comment by leventov** [comment]
Another option is to pre-generate your classes and copy them to source code, for example, see http://blog.siteos.de/java/javaee/chroniclemap/2016/05/16/How-To-Use-ChronicleMap-With-JavaEE.html

(this blog post that dynamic source code loading issues are still not resolved fully even for Chronicle Values. However, I'm going to add an option to generate Chronicle Values implementation classes in compile-time.)

**Comment by barabaka** [comment]
@leventov Got it, thanks for detailed explanation and links!

**Comment by RobAustin** [comment]
closing as we no longer provide support to chronicle map v2
