### ISSUE TITLE
error: must have a getter & setter, or getAt & setAt, or busyLock & unlock

### ISSUE THREAD

**Issue by zhuyoulong** [OpenHFT/Chronicle-Map#93]
**BuildData is a method, but the exception is displayed as Field, feel wrong, please help me to see**
my javabean code：
`public class NumberGroup implements ICacheModel {

    private Integer groupCity;  //NUMBER(3) not null,
    private Integer groupType;  //NUMBER(4) not null,
    private Long groupId;//      NUMBER(15) not null,
    private Integer memberCity;//   NUMBER(3) not null,
    private Long memberNumber;// NUMBER(15) not null,
    private Integer numberType;//   NUMBER(2) not null,
    private Long inureTime;//    DATE not null,
    private Long expireTime;//   DATE not null,
    private Long createTime;//   DATE not null,
    private Long modifyTime;//   DATE not null

    @Override
    public void buildData(ResultSet rs) throws Exception {

    }
...
`
java.lang.IllegalArgumentException: Field buildData must have a getter & setter, or getAt & setAt, or busyLock & unlock.
	at net.openhft.lang.model.DataValueModelImpl.<init>(DataValueModelImpl.java:220)
	at net.openhft.lang.model.DataValueModels.acquireModel(DataValueModels.java:46)
	at net.openhft.lang.model.DataValueGenerator.firstPrimitiveFieldType(DataValueGenerator.java:96)
	at net.openhft.chronicle.map.ChronicleMapBuilder.valueAlignment(ChronicleMapBuilder.java:636)
	at net.openhft.chronicle.map.ChronicleMapBuilder.entrySizeInfo(ChronicleMapBuilder.java:474)
	at net.openhft.chronicle.map.ChronicleMapBuilder.averageChunksPerEntry(ChronicleMapBuilder.java:574)
	at net.openhft.chronicle.map.ChronicleMapBuilder.trySegments(ChronicleMapBuilder.java:816)
	at net.openhft.chronicle.map.ChronicleMapBuilder.actualSegments(ChronicleMapBuilder.java:801)
	at net.openhft.chronicle.map.ChronicleMapBuilder.segmentHeaderSize(ChronicleMapBuilder.java:824)
	at net.openhft.chronicle.map.VanillaChronicleMap.<init>(VanillaChronicleMap.java:176)
	at net.openhft.chronicle.map.ChronicleMapBuilder.newMap(ChronicleMapBuilder.java:1389)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createWithFile(ChronicleMapBuilder.java:1316)
	at net.openhft.chronicle.map.ChronicleMapBuilder.createPersistedTo(ChronicleMapBuilder.java:1250)

**Comment by leventov** [comment]
1) try use Chronicle Map 3 if possible
2) seems that your key or value class is not a subtype of Serializable, not a value interface, and custom serializers not provided.

**Comment by zhuyoulong** [comment]
I try ,many thanks

**Comment by zhuyoulong** [comment]
I‘ll try,many thanks

**Comment by zhuyoulong** [comment]
**I found a thread blocking problem, is not it can be replaced by log4j2 log component**
Exceptions are as follows：
`"cache_batch_thread-main-4" prio=10 tid=0x00007f5624002000 nid=0x5404 waiting for monitor entry [0x00007f5660bc1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:231)
        - waiting to lock <0x0000000696820a28> (a org.apache.log4j.RollingFileAppender)
        at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
        at org.apache.log4j.Category.callAppenders(Category.java:193)
        at org.apache.log4j.Category.forcedLog(Category.java:365)
        at org.apache.log4j.Category.log(Category.java:772)
        at org.ops4j.pax.logging.service.internal.PaxLoggerImpl.inform(PaxLoggerImpl.java:143)
        at org.ops4j.pax.logging.internal.TrackingLogger.inform(TrackingLogger.java:86)
        at org.ops4j.pax.logging.slf4j.Slf4jLogger.info(Slf4jLogger.java:476)
        at net.openhft.chronicle.map.VanillaChronicleMap$Segment.writeUnlock(VanillaChronicleMap.java:1954)
        at net.openhft.chronicle.map.VanillaChronicleMap$Segment.put3(VanillaChronicleMap.java:2247)
        at net.openhft.chronicle.map.VanillaChronicleMap.put2(VanillaChronicleMap.java:613)
        at net.openhft.chronicle.map.VanillaChronicleMap.put1(VanillaChronicleMap.java:597)
        at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:554)
        at com.newland.sri.ccp.rtc.cache.common.BaseChronicleMapHelper.appendBatchCacheDatasByChm(BaseChronicleMapHelper.java:241)
        at com.newland.sri.ccp.rtc.cache.cacheserver.db.DbMgrImpl$BatchLoadDatasMapThread.run(DbMgrImpl.java:414)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)`

**Comment by leventov** [comment]
You can disable Log4j or SLF4J logging in Chronicle Map's packages (`net.openhft.chronicle.*`)

**Comment by zhuyoulong** [comment]
thank you

**Comment by zhuyoulong** [comment]
I have a question about the storage, Please help me to see, thank you, I use the power PC IBM stored procedures appear as follows：
`java.lang.NullPointerException
	at net.openhft.lang.io.NativeBytes.compareAndSwapLong(NativeBytes.java:555)
	at net.openhft.lang.io.AbstractBytes.tryRWWriteLock(AbstractBytes.java:2983)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.writeLock(VanillaChronicleMap.java:1898)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.writeLock(VanillaChronicleMap.java:1889)
	at net.openhft.chronicle.map.VanillaChronicleMap$Segment.put3(VanillaChronicleMap.java:2239)
	at net.openhft.chronicle.map.VanillaChronicleMap.put2(VanillaChronicleMap.java:613)
	at net.openhft.chronicle.map.VanillaChronicleMap.put1(VanillaChronicleMap.java:597)
	at net.openhft.chronicle.map.VanillaChronicleMap.put(VanillaChronicleMap.java:554)
	at com.newland.sri.ccp.rtc.cache.common.BaseChronicleMapHelper.appendBatchCacheDatasByChm(BaseChronicleMapHelper.java:245)
	at com.newland.sri.ccp.rtc.cache.cacheserver.db.DbMgrImpl$BatchLoadDatasMapThread.run(DbMgrImpl.java:414)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:781)`
