### ISSUE TITLE
CPU spinning at 100%

### ISSUE THREAD

**Issue by panghy** [OpenHFT/Chronicle-Map#95]
We often see processes run at 100% CPU with threads RUNNABLE:

`at net.openhft.chronicle.hash.impl.BigSegmentHeader.tryReadLockMillis(BigSegmentHeader.java:213)
    at net.openhft.chronicle.hash.impl.BigSegmentHeader.tryReadLock0(BigSegmentHeader.java:181)
    at net.openhft.chronicle.hash.impl.BigSegmentHeader.innerTryReadLock(BigSegmentHeader.java:171)
    at net.openhft.chronicle.hash.impl.BigSegmentHeader.readLock(BigSegmentHeader.java:144)
    at net.openhft.chronicle.map.VanillaChronicleMap.optimizedGet(VanillaChronicleMap.java:379)
    at net.openhft.chronicle.map.VanillaChronicleMap.get(VanillaChronicleMap.java:331)
`

We use only single key gets and puts and it's odd that it would spin at 100% CPU for something like this. It gets stuck for minutes before resolving. Often times it's better to just kill the process instead of waiting.

This can be seen in 3.9 and 3.10.

**Comment by panghy** [comment]
Another example:

`   java.lang.Thread.State: RUNNABLE
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.keyEquals(CompiledMapQueryContext.java:2974)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initKeySearch(CompiledMapQueryContext.java:3767)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.searchState(CompiledMapQueryContext.java:3784)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.searchStatePresent(CompiledMapQueryContext.java:3806)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.initPresenceOfEntry(CompiledMapQueryContext.java:3854)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.entryPresence(CompiledMapQueryContext.java:3863)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.entryPresent(CompiledMapQueryContext.java:3873)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.entry(CompiledMapQueryContext.java:4031)
	at net.openhft.chronicle.map.impl.CompiledMapQueryContext.entry(CompiledMapQueryContext.java:66)
	at net.openhft.chronicle.map.MapMethods.containsKey(MapMethods.java:44)
	at net.openhft.chronicle.map.VanillaChronicleMap.containsKey(VanillaChronicleMap.java:554)
	at net.openhft.chronicle.map.AbstractChronicleMap$2.contains(AbstractChronicleMap.java:157)
`

**Comment by panghy** [comment]
In all of these cases, the persisted map cannot be reused and has to be purged. Simply operating on the map after a JVM restart will hang again. Recovery will probably help but I think it calls into question the reliability of the maps if we they need recovery (after it chews through 64 cores of CPU =p for minutes, kill -9, purge/recover file, restart).

We will also try using non-persisted maps (which obviously will not have to be purged).

**Comment by leventov** [comment]
I think this is closely related to some recent discussions: https://groups.google.com/d/msg/java-chronicle/APHa04f1IlA/p1bEJ2C9BAAJ, https://groups.google.com/d/msg/java-chronicle/_yytqxG7NZs/MHWocB_9BwAJ, and this issue: #79 

I don't understand this:
> It gets stuck for minutes before resolving.

Chronicle Map spins for 2 minutes trying to acquire locks, and if unsuccessful, it throws an Exception. Do you mean a thrown exception under "resolution"?

---

So if you `kill -9` a JVM process while it acesses a map, some locks may remain in acquired state, and there is no way to clear them, other than perform recovery: https://github.com/OpenHFT/Chronicle-Map#recovery. Some solutions to mitigate this situation are suggested here: https://groups.google.com/d/msg/java-chronicle/APHa04f1IlA/4Ivs3X_IBAAJ and here: https://github.com/OpenHFT/Chronicle-Map/issues/79#issuecomment-210227919

**Comment by minborg** [comment]
I am closing this issue. Please reopen if the problem can be seen again. I think spinning on a lock that's been left behind due to a previous crash and where no recovery operation was performed is ok.
